INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (5, '', 'Anglais', 'English', 1);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (6, '', 'Sciences Physiques', 'Physical Sciences', 1);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (31, '', 'History', 'History', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (32, '', 'Literature in English', 'Literature in English', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (33, '', 'French', 'French', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (34, '', 'English Language', 'English Language', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (35, '', 'Philosophy', 'Philosophy', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (36, '', 'ICT', 'ICT', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (37, '', 'Manual Labour', 'Manual Labour', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (38, '', 'Physical Education', 'Physical Education', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (39, '', 'History', 'History', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (40, '', 'Economics', 'Economics', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (41, '', 'Geography', 'Geography', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (42, '', 'English Language', 'English Language', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (43, '', 'Philosophy', 'Philosophy', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (44, '', 'ICT', 'ICT', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (45, '', 'Manual Labour', 'Manual Labour', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (46, '', 'Physical Education', 'Physical Education', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (47, '', 'History', 'History', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (48, '', 'Economics', 'Economics', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (49, '', 'Literature in English', 'Literature in English', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (50, '', 'English Language', 'English Language', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (51, '', 'Philosophy', 'Philosophy', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (52, '', 'ICT', 'ICT', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (53, '', 'Manual Labour', 'Manual Labour', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (54, '', 'Physical Education', 'Physical Education', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (55, '', 'Mathematics', 'Mathematics', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (56, '', 'Economics', 'Economics', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (57, '', 'Geography', 'Geography', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (58, '', 'English Language', 'English Language', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (59, '', 'Philosophy', 'Philosophy', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (60, '', 'ICT', 'ICT', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (61, '', 'Manual Labour', 'Manual Labour', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (62, '', 'Physical Education', 'Physical Education', 10);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (67, '', 'History', 'History', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (68, '', 'Litereature in English', 'Litereature in English', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (69, '', 'English Language', 'English Language', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (70, '', 'Philosophy', 'Philosophy', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (71, '', 'ICT', 'ICT', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (72, '', 'Manual Labour', 'Manual Labour', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (73, '', 'Physical Education', 'Physical Education', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (74, '', 'Chemistry', 'Chemistry', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (75, '', 'Biology', 'Biology', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (76, '', 'Physics', 'Physics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (77, '', 'Mathematics', 'Mathematics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (78, '', 'Further Mathematics', 'Further Mathematics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (79, '', 'Computer Science', 'Computer Science', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (80, '', 'Food Science', 'Food Science', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (81, '', 'Manual labour', 'Manual labour', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (83, '', 'Chemistry', 'Chemistry', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (84, '', 'Biology', 'Biology', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (85, '', 'Physics', 'Physics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (86, '', 'Mathematics', 'Mathematics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (87, '', 'Further Mathematics', 'Further Mathematics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (88, '', 'Computer Science', 'Computer Science', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (89, '', 'Food Science', 'Food Science', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (90, '', 'Manual labour', 'Manual labour', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (92, '', 'Chemistry', 'Chemistry', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (93, '', 'Biology', 'Biology', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (94, '', 'Mathematics', 'Mathematics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (95, '', 'ICT', 'ICT', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (96, '', 'Food Science', 'Food Science', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (97, '', 'Manual labour', 'Manual labour', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (98, '', 'Physical Education', 'Physical Education', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (99, '', 'English Language', 'English Language', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (100, '', 'Chemistry', 'Chemistry', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (101, '', 'Biology', 'Biology', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (102, '', 'Geology', 'Geology', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (103, '', 'ICT', 'ICT', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (104, '', 'Food Science', 'Food Science', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (105, '', 'Manual labour', 'Manual labour', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (106, '', 'Physical Education', 'Physical Education', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (107, '', 'English Language', 'English Language', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (108, '', 'Chemistry', 'Chemistry', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (109, '', 'Biology', 'Biology', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (110, '', 'ICT', 'ICT', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (111, '', 'Food Science', 'Food Science', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (112, '', 'Manual labour', 'Manual labour', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (113, '', 'Physical Education', 'Physical Education', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (114, '', 'English Language', 'English Language', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (115, '', 'History', 'History', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (116, '', 'Literature in English', 'Literature in English', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (117, '', 'French', 'French', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (118, '', 'English Language', 'English Language', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (119, '', 'Philosophy', 'Philosophy', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (120, '', 'ICT', 'ICT', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (121, '', 'Physical Education', 'Physical Education', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (122, '', 'History', 'History', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (123, '', 'Economics', 'Economics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (124, '', 'Geography', 'Geography', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (125, '', 'English Language', 'English Language', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (126, '', 'Philosophy', 'Philosophy', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (127, '', 'ICT', 'ICT', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (128, '', 'Physical Education', 'Physical Education', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (129, '', 'History', 'History', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (130, '', 'Economics', 'Economics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (131, '', 'Literature in English', 'Literature in English', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (132, '', 'English Language', 'English Language', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (133, '', 'Philosophy', 'Philosophy', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (134, '', 'ICT', 'ICT', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (135, '', 'Physical Education', 'Physical Education', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (136, '', 'Mathematics', 'Mathematics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (137, '', 'Economics', 'Economics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (138, '', 'Geography', 'Geography', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (139, '', 'English Language', 'English Language', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (140, '', 'Philosophy', 'Philosophy', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (141, '', 'ICT', 'ICT', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (142, '', 'Physical Education', 'Physical Education', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (143, '', 'History', 'History', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (144, '', 'Litereature in English', 'Litereature in English', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (145, '', 'English Language', 'English Language', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (146, '', 'Philosophy', 'Philosophy', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (147, '', 'ICT', 'ICT', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (148, '', 'Physical Education', 'Physical Education', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (149, '', 'Chemistry', 'Chemistry', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (150, '', 'Biology', 'Biology', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (151, '', 'Physics', 'Physics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (152, '', 'Mathematics', 'Mathematics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (153, '', 'Further Mathematics', 'Further Mathematics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (154, '', 'Computer Science', 'Computer Science', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (155, '', 'Food Science', 'Food Science', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (157, '', 'Chemistry', 'Chemistry', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (158, '', 'Biology', 'Biology', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (159, '', 'Physics', 'Physics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (160, '', 'Mathematics', 'Mathematics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (161, '', 'Further Mathematics', 'Further Mathematics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (162, '', 'Computer Science', 'Computer Science', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (163, '', 'Food Science', 'Food Science', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (165, '', 'Chemistry', 'Chemistry', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (166, '', 'Biology', 'Biology', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (167, '', 'Mathematics', 'Mathematics', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (168, '', 'ICT', 'ICT', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (169, '', 'Food Science', 'Food Science', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (170, '', 'Physical Education', 'Physical Education', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (171, '', 'English Language', 'English Language', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (177, '', 'Français ', 'Français ', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (178, '', 'Anglais ', 'Anglais ', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (341, '', 'Sport', 'Sport', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (342, '', 'Sportioo', 'Sportioo', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (360, '', 'Sportesss', 'Sportesss', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (429, '', 'Economics', 'Economics', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (430, '', 'French', 'French', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (431, '', 'Biology', 'Biology', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (432, '', 'Mathematics', 'Mathematics', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (437, '', 'Biology', 'Biology', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (438, '', 'English', 'English', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (439, '', 'French', 'French', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (440, '', 'Additional Mathemtics', 'Additional Mathemtics', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (441, '', 'citizenship', 'citizenship', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (442, '', 'Sport', 'Sport', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (443, '', 'Mathematics', 'Mathematics', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (444, '', 'History', 'History', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (445, '', 'Chemistry', 'Chemistry', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (452, '', 'English', 'English', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (453, '', 'Biology', 'Biology', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (454, '', 'Geography', 'Geography', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (455, '', 'Sport', 'Sport', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (456, '', 'French', 'French', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (457, '', 'Mathematics', 'Mathematics', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (458, '', 'English Language', 'English Language', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (459, '', 'French Language', 'French Language', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (460, '', 'Food & Nutrition', 'Food & Nutrition', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (461, '', 'Biology', 'Biology', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (462, '', 'Citizenship', 'Citizenship', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (463, '', 'Geography', 'Geography', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (464, '', 'Economics', 'Economics', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (465, '', 'Chemistry', 'Chemistry', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (502, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (503, '', 'Literature in English', 'Literature in English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (504, '', 'French', 'French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (505, '', 'History', 'History', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (506, '', 'Geography', 'Geography', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (507, '', 'Mathematics', 'Mathematics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (508, '', 'Citizenship', 'Citizenship', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (509, '', 'Physics', 'Physics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (510, '', 'Biology', 'Biology', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (511, '', 'Chemistry', 'Chemistry', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (512, '', 'Computer Science', 'Computer Science', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (513, '', 'Home Economics', 'Home Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (514, '', 'National Languages & Culture', 'National Languages & Culture', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (515, '', 'Manual Labour', 'Manual Labour', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (516, '', 'Physical Education', 'Physical Education', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (532, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (533, '', 'Literature in English', 'Literature in English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (534, '', 'French', 'French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (535, '', 'History', 'History', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (536, '', 'Geography', 'Geography', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (537, '', 'Mathematics', 'Mathematics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (538, '', 'Citizenship', 'Citizenship', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (539, '', 'Physics', 'Physics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (540, '', 'Biology', 'Biology', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (541, '', 'Chemistry', 'Chemistry', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (542, '', 'Computer Science', 'Computer Science', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (543, '', 'Home Economics', 'Home Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (544, '', 'National Languages & Culture', 'National Languages & Culture', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (545, '', 'Manual Labour', 'Manual Labour', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (546, '', 'Physical Education', 'Physical Education', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (547, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (548, '', 'Literature in English', 'Literature in English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (549, '', 'French', 'French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (550, '', 'History', 'History', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (551, '', 'Geography', 'Geography', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (552, '', 'Mathematics', 'Mathematics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (553, '', 'Citizenship', 'Citizenship', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (554, '', 'Physics', 'Physics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (555, '', 'Biology', 'Biology', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (556, '', 'Chemistry', 'Chemistry', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (557, '', 'Computer Science', 'Computer Science', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (558, '', 'Home Economics', 'Home Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (559, '', 'National Languages & Culture', 'National Languages & Culture', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (560, '', 'Manual Labour', 'Manual Labour', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (561, '', 'Physical Education', 'Physical Education', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (577, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (578, '', 'Literature in English', 'Literature in English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (579, '', 'Intensive French', 'Intensive French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (580, '', 'History', 'History', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (581, '', 'Geography', 'Geography', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (582, '', 'Mathematics', 'Mathematics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (583, '', 'Physics', 'Physics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (584, '', 'Biology', 'Biology', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (585, '', 'Chemistry', 'Chemistry', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (586, '', 'Computer Science', 'Computer Science', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (587, '', 'Home Economics', 'Home Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (588, '', 'National Languages & Culture', 'National Languages & Culture', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (589, '', 'Manual Labour', 'Manual Labour', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (590, '', 'Physical Education', 'Physical Education', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (591, '', 'Education à la city. et la morale', 'Education à la city. et la morale', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (592, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (593, '', 'Literature in English', 'Literature in English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (594, '', 'French', 'French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (595, '', 'History', 'History', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (596, '', 'Geography', 'Geography', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (597, '', 'Mathematics', 'Mathematics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (598, '', 'Citizenship', 'Citizenship', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (599, '', 'Physics', 'Physics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (600, '', 'Biology', 'Biology', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (601, '', 'Chemistry', 'Chemistry', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (602, '', 'Computer Science', 'Computer Science', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (603, '', 'Home Economic', 'Home Economic', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (604, '', 'National Languages & Culture', 'National Languages & Culture', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (605, '', 'Manual Labour', 'Manual Labour', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (606, '', 'Physical Education', 'Physical Education', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (607, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (608, '', 'Literature in English', 'Literature in English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (609, '', 'French', 'French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (610, '', 'History', 'History', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (611, '', 'Geography', 'Geography', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (612, '', 'Mathematics', 'Mathematics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (613, '', 'Citizenship', 'Citizenship', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (614, '', 'Physics', 'Physics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (615, '', 'Biology', 'Biology', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (616, '', 'Chemistry', 'Chemistry', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (617, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (618, '', 'Home Economics', 'Home Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (619, '', 'National Languages & Culture', 'National Languages & Culture', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (620, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (621, '', 'Physical Education', 'Physical Education', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (622, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (623, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (624, '', 'French', 'French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (625, '', 'History', 'History', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (626, '', 'Geography', 'Geography', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (627, '', 'Mathematics', 'Mathematics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (628, '', 'Citizenship', 'Citizenship', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (629, '', 'Physics', 'Physics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (630, '', 'Biology', 'Biology', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (631, '', 'Chemistry', 'Chemistry', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (632, '', 'Computer Science', 'Computer Science', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (633, '', 'Home Economics', 'Home Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (634, '', 'National Languages & Culture', 'National Languages & Culture', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (635, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (636, '', 'Physical Education', 'Physical Education', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (637, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (638, '', 'Literature in English', 'Literature in English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (639, '', 'French', 'French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (640, '', 'History', 'History', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (641, '', 'Geography', 'Geography', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (642, '', 'Mathematics', 'Mathematics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (643, '', 'Citizenship', 'Citizenship', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (644, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (645, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (646, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (647, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (648, '', 'Home Economics', 'Home Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (649, '', 'National Languages & Culture', 'National Languages & Culture', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (650, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (651, '', 'Physical Education', 'Physical Education', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (682, '', 'Economics', 'Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (683, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (684, '', 'Literature in English', 'Literature in English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (685, '', 'French', 'French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (686, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (687, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (688, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (689, '', 'Citizenship ', 'Citizenship ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (690, '', 'Physics', 'Physics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (691, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (692, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (693, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (694, '', 'Home Economics', 'Home Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (695, '', 'Logic', 'Logic', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (696, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (697, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (716, '', 'Economics ', 'Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (717, '', 'English ', 'English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (718, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (719, '', 'French ', 'French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (720, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (721, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (722, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (723, '', 'Citizenship ', 'Citizenship ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (724, '', 'Physics', 'Physics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (725, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (726, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (727, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (728, '', 'Home Economics ', 'Home Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (729, '', 'Logic ', 'Logic ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (730, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (731, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (748, '', 'Economics', 'Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (749, '', 'English ', 'English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (750, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (751, '', 'French', 'French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (752, '', 'History', 'History', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (753, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (754, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (755, '', 'Citizenship ', 'Citizenship ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (756, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (757, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (758, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (759, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (760, '', 'Home Economics ', 'Home Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (761, '', 'Logic ', 'Logic ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (762, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (764, '', 'Economics', 'Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (765, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (766, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (767, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (768, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (769, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (770, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (771, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (772, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (773, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (774, '', 'Home Economics ', 'Home Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (775, '', 'Logic ', 'Logic ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (776, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (777, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (778, '', 'Intensive French ', 'Intensive French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (779, '', 'Economics', 'Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (780, '', 'English ', 'English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (781, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (782, '', 'French ', 'French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (783, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (784, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (785, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (786, '', 'Citizenship ', 'Citizenship ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (787, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (788, '', 'Commerce ', 'Commerce ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (789, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (790, '', 'Food & Nutrition ', 'Food & Nutrition ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (791, '', 'Logic ', 'Logic ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (792, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (793, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (794, '', 'Economics', 'Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (795, '', 'English ', 'English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (796, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (797, '', 'French ', 'French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (798, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (799, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (800, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (801, '', 'Citizenship ', 'Citizenship ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (802, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (803, '', 'Commerce ', 'Commerce ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (804, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (805, '', 'Food & Nutrition ', 'Food & Nutrition ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (806, '', 'Logic ', 'Logic ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (807, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (808, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (809, '', 'Economics ', 'Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (810, '', 'English ', 'English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (811, '', 'French ', 'French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (812, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (813, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (814, '', 'Citizenship ', 'Citizenship ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (815, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (816, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (817, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (818, '', 'Additionally Mathematics ', 'Additionally Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (819, '', 'Human Biology ', 'Human Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (820, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (821, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (822, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (840, '', 'Economics', 'Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (841, '', 'English ', 'English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (842, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (843, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (844, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (845, '', 'Intensive French ', 'Intensive French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (846, '', 'Education à la city. et la morale', 'Education à la city. et la morale', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (847, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (848, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (849, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (850, '', 'Additionally Mathematics ', 'Additionally Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (851, '', 'Human Biology ', 'Human Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (852, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (853, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (854, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (856, '', 'Economics', 'Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (857, '', 'English ', 'English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (858, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (859, '', 'French ', 'French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (860, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (861, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (862, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (863, '', 'Citizenship ', 'Citizenship ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (864, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (865, '', 'Commerce ', 'Commerce ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (866, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (867, '', 'Food & Nutrition ', 'Food & Nutrition ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (868, '', 'Religious Studies ', 'Religious Studies ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (869, '', 'Logic ', 'Logic ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (870, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (871, '', 'Economics', 'Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (872, '', 'English ', 'English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (873, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (874, '', 'French ', 'French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (875, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (876, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (877, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (878, '', 'Citizenship ', 'Citizenship ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (879, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (880, '', 'Commerce ', 'Commerce ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (881, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (882, '', 'Food & Nutrition ', 'Food & Nutrition ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (883, '', 'Religious Studies ', 'Religious Studies ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (884, '', 'Logic', 'Logic', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (885, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (886, '', 'Economics ', 'Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (887, '', 'English ', 'English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (888, '', 'French ', 'French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (889, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (890, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (891, '', 'Citizenship ', 'Citizenship ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (892, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (893, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (894, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (895, '', 'Additionally Mathematics ', 'Additionally Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (896, '', 'Human Biology ', 'Human Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (897, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (898, '', 'Religious Studies ', 'Religious Studies ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (900, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (901, '', 'Economics ', 'Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (902, '', 'English ', 'English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (903, '', 'French ', 'French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (904, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (905, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (906, '', 'Citizenship ', 'Citizenship ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (907, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (908, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (909, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (910, '', 'Additionally Mathematics ', 'Additionally Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (911, '', 'Human Biology ', 'Human Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (912, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (913, '', 'Religious Studies ', 'Religious Studies ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (914, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (931, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (932, '', 'French', 'French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (933, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (934, '', 'Philosophy ', 'Philosophy ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (935, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (936, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (937, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (938, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (939, '', 'Economics ', 'Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (940, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (941, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (942, '', 'English Language ', 'English Language ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (943, '', 'Philosophy ', 'Philosophy ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (944, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (945, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (946, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (947, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (948, '', 'Economics ', 'Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (949, '', 'English Language ', 'English Language ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (950, '', 'Philosophy ', 'Philosophy ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (951, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (952, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (953, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (954, '', 'Economics ', 'Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (955, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (956, '', 'Pure Maths & Statistics ', 'Pure Maths & Statistics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (957, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (958, '', 'Philosophy ', 'Philosophy ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (959, '', 'English Language ', 'English Language ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (960, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (961, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (962, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (963, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (964, '', 'Philosophy ', 'Philosophy ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (965, '', 'English Language ', 'English Language ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (966, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (967, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (968, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (980, '', 'Maths Mechanics ', 'Maths Mechanics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (981, '', 'Pure Maths & Statistics ', 'Pure Maths & Statistics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (982, '', 'Further Maths', 'Further Maths', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (983, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (984, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (985, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (986, '', 'Food Science ', 'Food Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (987, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (988, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (990, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (991, '', 'Maths Mechanics ', 'Maths Mechanics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (992, '', 'Pure Maths & Statistics ', 'Pure Maths & Statistics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (993, '', 'Further Maths ', 'Further Maths ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (994, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (995, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (996, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (997, '', 'Food Science ', 'Food Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (998, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (999, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1001, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1013, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1014, '', 'French ', 'French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1015, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1016, '', 'Philosophy ', 'Philosophy ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1017, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1018, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1019, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1020, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1021, '', 'Economics ', 'Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1022, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1023, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1024, '', 'English Language ', 'English Language ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1025, '', 'Philosophy ', 'Philosophy ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1026, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1027, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1036, '', 'Economics ', 'Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1037, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1038, '', 'Pure Maths & Statistics ', 'Pure Maths & Statistics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1039, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1040, '', 'Philosophy ', 'Philosophy ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1041, '', 'English Language ', 'English Language ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1042, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1043, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1044, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1045, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1046, '', 'Philosophy ', 'Philosophy ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1047, '', 'English Language ', 'English Language ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1048, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1049, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1050, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1051, '', 'Maths Mechanics ', 'Maths Mechanics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1052, '', 'Pure Maths & Statistics ', 'Pure Maths & Statistics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1053, '', 'Further Maths', 'Further Maths', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1054, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1055, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1056, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1057, '', 'Food Science ', 'Food Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1058, '', 'ICT ', 'ICT ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1059, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1061, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1062, '', 'Maths Mechanics ', 'Maths Mechanics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1063, '', 'Pure Maths & Statistics ', 'Pure Maths & Statistics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1064, '', 'Further Maths ', 'Further Maths ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1065, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1066, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1067, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1068, '', 'Food Science ', 'Food Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1069, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1070, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1072, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1073, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1074, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1075, '', 'French ', 'French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1076, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1077, '', 'Geography', 'Geography', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1078, '', 'Mathematics', 'Mathematics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1079, '', 'Citizenship', 'Citizenship', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1080, '', 'Physics', 'Physics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1081, '', 'Biology', 'Biology', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1082, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1083, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1084, '', 'Home Economics', 'Home Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1085, '', 'National Languages & Cultures ', 'National Languages & Cultures ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1086, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1087, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1098, '', 'Maths Mechanics ', 'Maths Mechanics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1099, '', 'Pure Maths & Statistics ', 'Pure Maths & Statistics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1100, '', 'Further Maths', 'Further Maths', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1101, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1102, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1103, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1104, '', 'Food Science ', 'Food Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1105, '', 'ICT ', 'ICT ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1106, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1107, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1108, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1160, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1161, '', 'Literature in English', 'Literature in English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1162, '', 'French', 'French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1163, '', 'History', 'History', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1164, '', 'Geography', 'Geography', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1165, '', 'Mathematics', 'Mathematics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1166, '', 'Citizenship', 'Citizenship', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1167, '', 'Physics', 'Physics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1168, '', 'Biology', 'Biology', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1169, '', 'Chemistry', 'Chemistry', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1170, '', 'Computer Science', 'Computer Science', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1171, '', 'Home Economics', 'Home Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1172, '', 'National Languages & Culture', 'National Languages & Culture', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1173, '', 'Manual Labour', 'Manual Labour', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1174, '', 'Physical Education', 'Physical Education', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1190, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1191, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1192, '', 'Intensive French', 'Intensive French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1193, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1194, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1195, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1196, '', 'Education à la city. et la morale', 'Education à la city. et la morale', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1197, '', 'Physics', 'Physics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1198, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1199, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1200, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1201, '', 'Home Economics ', 'Home Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1202, '', 'National Languages & Cultures ', 'National Languages & Cultures ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1203, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1204, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1205, '', 'Economics', 'Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1206, '', 'English ', 'English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1207, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1208, '', 'French ', 'French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1209, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1210, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1211, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1212, '', 'Citizenship ', 'Citizenship ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1213, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1214, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1215, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1216, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1217, '', 'Home Economics ', 'Home Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1218, '', 'Logic ', 'Logic ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1219, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1220, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1221, '', 'Economics', 'Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1222, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1223, '', 'Literature in English', 'Literature in English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1224, '', 'French ', 'French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1225, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1226, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1227, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1228, '', 'Citizenship ', 'Citizenship ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1229, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1230, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1231, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1232, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1233, '', 'Home Economics ', 'Home Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1234, '', 'Logic ', 'Logic ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1235, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1236, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1237, '', 'Economics ', 'Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1238, '', 'English ', 'English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1239, '', 'French ', 'French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1240, '', 'History', 'History', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1241, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1242, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1243, '', 'Citizenship ', 'Citizenship ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1244, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1245, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1246, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1247, '', 'Additionally Mathematics ', 'Additionally Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1248, '', 'Human Biology ', 'Human Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1249, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1250, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1251, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1252, '', 'English ', 'English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1253, '', 'Geography ', 'Geography ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1254, '', 'Education à la city. et la morale', 'Education à la city. et la morale', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1255, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1256, '', 'Human Biology ', 'Human Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1257, '', 'Computer Science ', 'Computer Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1258, '', 'Economics ', 'Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1259, '', 'Intensive French ', 'Intensive French ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1260, '', 'Mathematics ', 'Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1261, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1262, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1263, '', 'Additionally Mathematics ', 'Additionally Mathematics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1264, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1265, '', 'Religious Studies ', 'Religious Studies ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1266, '', 'Maths Mechanics ', 'Maths Mechanics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1267, '', 'Pure Maths & Statistics ', 'Pure Maths & Statistics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1268, '', 'Further Maths', 'Further Maths', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1269, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1270, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1271, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1272, '', 'Food Science ', 'Food Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1273, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1274, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1275, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1276, '', 'Maths Mechanics ', 'Maths Mechanics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1277, '', 'Pure Maths & Statistics ', 'Pure Maths & Statistics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1278, '', 'Further Maths ', 'Further Maths ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1279, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1280, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1281, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1282, '', 'Food Science ', 'Food Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1283, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1284, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1285, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1286, '', 'Literature in English ', 'Literature in English ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1287, '', 'History ', 'History ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1288, '', 'Economics ', 'Economics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1289, '', 'English Language ', 'English Language ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1290, '', 'Philosophy ', 'Philosophy ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1291, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1292, '', 'Physical Education ', 'Physical Education ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1293, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1294, '', 'Maths Mechanics', 'Maths Mechanics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1295, '', 'Pure Maths & Statistics ', 'Pure Maths & Statistics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1296, '', 'Further Maths', 'Further Maths', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1297, '', 'Physics ', 'Physics ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1298, '', 'Biology ', 'Biology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1299, '', 'Chemistry ', 'Chemistry ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1300, '', 'Food Science ', 'Food Science ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1301, '', 'ICT', 'ICT', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1302, '', 'Geology ', 'Geology ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1303, '', 'Manual Labour ', 'Manual Labour ', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1304, '', 'English', 'English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1305, '', 'Literature in English', 'Literature in English', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1306, '', 'French', 'French', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1307, '', 'History', 'History', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1308, '', 'Geography', 'Geography', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1309, '', 'Mathematics', 'Mathematics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1310, '', 'Citizenship', 'Citizenship', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1311, '', 'Physics', 'Physics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1312, '', 'Biology', 'Biology', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1313, '', 'Chemistry', 'Chemistry', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1314, '', 'Computer Science', 'Computer Science', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1315, '', 'Home Economics', 'Home Economics', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1316, '', 'National Languages & Culture', 'National Languages & Culture', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1317, '', 'Manual Labour', 'Manual Labour', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1318, '', 'Physical Education', 'Physical Education', 17);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1322, '', 'Sport', 'Sport', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1323, '', 'Technology', 'Technology', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1324, '', 'French', 'French', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1325, '', 'Technology', 'Technology', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1326, '', 'French', 'French', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1327, '', 'Mathematic', 'Mathematic', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1328, '', 'Electricity', 'Electricity', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1329, '', 'Construction', 'Construction', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1330, '', 'Mechanics', 'Mechanics', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1331, '', 'Sewing', 'Sewing', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1332, '', 'Technology', 'Technology', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1333, '', 'Fashion and Fabric', 'Fashion and Fabric', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1334, '', 'Technical Drawing', 'Technical Drawing', 16);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1335, '', 'Math', 'Math', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1336, '', 'Histoire', 'Histoire', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1337, '', 'Geographie', 'Geographie', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1338, '', 'Science', 'Science', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1339, '', 'Travail Manuel ', 'Travail Manuel ', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1340, '', 'Le Test', 'Le Test', 15);
INSERT INTO subjects (id, name, name_fr, name_en, school_id) VALUES (1341, '', 'L''autre Test', 'L''autre Test', 15);
