CREATE TABLE public.academic_years (
    id integer NOT NULL,
    name text NOT NULL,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    school_id integer NOT NULL,
    is_active boolean DEFAULT false
);
CREATE TABLE public.archive_access_logs (
    id integer NOT NULL,
    archive_id integer,
    school_id integer NOT NULL,
    user_id integer NOT NULL,
    action text NOT NULL,
    ip text,
    user_agent text,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.archived_documents (
    id integer NOT NULL,
    school_id integer NOT NULL,
    type text NOT NULL,
    bulletin_id integer,
    class_id integer NOT NULL,
    academic_year text NOT NULL,
    term text NOT NULL,
    student_id integer,
    language text NOT NULL,
    filename text NOT NULL,
    storage_key text NOT NULL,
    checksum_sha256 text NOT NULL,
    size_bytes bigint NOT NULL,
    recipients jsonb,
    snapshot jsonb,
    meta jsonb,
    version text DEFAULT '1.0'::text,
    sent_at timestamp without time zone NOT NULL,
    sent_by integer NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.assigned_fees (
    id integer NOT NULL,
    school_id integer NOT NULL,
    student_id integer NOT NULL,
    fee_structure_id integer NOT NULL,
    original_amount integer NOT NULL,
    discount_amount integer DEFAULT 0,
    discount_reason text,
    final_amount integer NOT NULL,
    paid_amount integer DEFAULT 0,
    balance_amount integer NOT NULL,
    status text DEFAULT 'pending'::text,
    due_date timestamp without time zone NOT NULL,
    paid_date timestamp without time zone,
    last_payment_date timestamp without time zone,
    term_id integer,
    academic_year_id integer,
    reminder_sent boolean DEFAULT false,
    reminder_sent_at timestamp without time zone,
    overdue_notice_sent boolean DEFAULT false,
    overdue_notice_sent_at timestamp without time zone,
    notes text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.attendance (
    id integer NOT NULL,
    student_id integer NOT NULL,
    class_id integer NOT NULL,
    date timestamp without time zone NOT NULL,
    status text NOT NULL,
    teacher_id integer NOT NULL,
    parent_notified boolean DEFAULT false,
    notification_sent_at timestamp without time zone,
    reason text,
    created_at timestamp without time zone DEFAULT now(),
    school_id integer,
    time_in timestamp without time zone,
    time_out timestamp without time zone,
    notes text,
    marked_by integer,
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.audit_log_access_tracking (
    id integer NOT NULL,
    accessed_by integer NOT NULL,
    filters jsonb,
    results_count integer,
    ip_address text,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.audit_logs (
    id integer NOT NULL,
    user_id integer,
    user_role text,
    user_email text,
    action text NOT NULL,
    action_category text NOT NULL,
    entity_type text,
    entity_id text,
    description text NOT NULL,
    metadata jsonb,
    ip_address text,
    user_agent text,
    school_id integer,
    severity text DEFAULT 'info'::text,
    success boolean DEFAULT true,
    error_message text,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.bulletin_comprehensive (
    id integer NOT NULL,
    student_id integer NOT NULL,
    class_id integer NOT NULL,
    school_id integer NOT NULL,
    term text NOT NULL,
    academic_year text NOT NULL,
    unjustified_absence_hours numeric(5,2) DEFAULT 0.00,
    justified_absence_hours numeric(5,2) DEFAULT 0.00,
    lateness_count integer DEFAULT 0,
    detention_hours numeric(5,2) DEFAULT 0.00,
    conduct_warning boolean DEFAULT false,
    conduct_blame boolean DEFAULT false,
    exclusion_days integer DEFAULT 0,
    permanent_exclusion boolean DEFAULT false,
    total_general numeric(8,2),
    general_average numeric(5,2),
    trimester_average numeric(5,2),
    number_of_averages integer,
    success_rate numeric(5,2),
    class_profile jsonb,
    work_appreciation text,
    general_comment text,
    parent_visa jsonb,
    teacher_visa jsonb,
    headmaster_visa jsonb,
    entered_by integer,
    last_modified_by integer,
    data_source text DEFAULT 'manual'::text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    status text DEFAULT 'draft'::text,
    submitted_at timestamp without time zone,
    approved_at timestamp without time zone,
    sent_at timestamp without time zone,
    approved_by integer,
    notifications_sent jsonb,
    class_council_decisions text,
    class_council_mentions text,
    orientation_recommendations text,
    council_date text,
    council_participants text
);
CREATE TABLE public.bulletin_notifications (
    id integer NOT NULL,
    bulletin_id integer NOT NULL,
    recipient_type text NOT NULL,
    recipient_id integer NOT NULL,
    recipient_email text,
    recipient_phone text,
    email_sent boolean DEFAULT false,
    sms_sent boolean DEFAULT false,
    whatsapp_sent boolean DEFAULT false,
    push_notification_sent boolean DEFAULT false,
    email_delivered boolean DEFAULT false,
    sms_delivered boolean DEFAULT false,
    whatsapp_delivered boolean DEFAULT false,
    email_opened boolean DEFAULT false,
    email_opened_at timestamp without time zone,
    bulletin_downloaded boolean DEFAULT false,
    bulletin_downloaded_at timestamp without time zone,
    bulletin_viewed boolean DEFAULT false,
    bulletin_viewed_at timestamp without time zone,
    notification_language text DEFAULT 'fr'::text,
    delivery_metadata jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.bulletin_subject_codes (
    id integer NOT NULL,
    bulletin_comprehensive_id integer NOT NULL,
    student_id integer NOT NULL,
    subject_id integer NOT NULL,
    subject_name text NOT NULL,
    ctba numeric(5,2),
    cba numeric(5,2),
    ca numeric(5,2),
    cma numeric(5,2),
    cote text,
    cna text,
    min_grade numeric(5,2),
    max_grade numeric(5,2),
    competency_level text,
    teacher_comment text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.bulletin_verifications (
    id integer NOT NULL,
    verification_code text NOT NULL,
    short_code text NOT NULL,
    bulletin_id integer NOT NULL,
    student_id integer NOT NULL,
    school_id integer NOT NULL,
    class_id integer NOT NULL,
    term text NOT NULL,
    academic_year text NOT NULL,
    student_name text NOT NULL,
    student_matricule text NOT NULL,
    student_birth_date text,
    student_gender text,
    class_name text NOT NULL,
    school_name text NOT NULL,
    general_average text,
    class_rank integer,
    total_students integer,
    verification_hash text NOT NULL,
    digital_signature text,
    qr_code_data text NOT NULL,
    qr_code_image text,
    is_active boolean DEFAULT true,
    verification_count integer DEFAULT 0,
    last_verified_at timestamp without time zone,
    last_verified_ip text,
    issued_by integer NOT NULL,
    issued_at timestamp without time zone DEFAULT now(),
    approved_by integer,
    approved_at timestamp without time zone,
    expires_at timestamp without time zone,
    issue_metadata jsonb,
    security_level text DEFAULT 'standard'::text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.bulletin_workflow (
    id integer NOT NULL,
    student_id integer NOT NULL,
    class_id integer NOT NULL,
    school_id integer NOT NULL,
    term text NOT NULL,
    academic_year text NOT NULL,
    current_status text DEFAULT 'awaiting_teacher_submissions'::text NOT NULL,
    total_subjects integer NOT NULL,
    completed_subjects integer DEFAULT 0,
    missing_subjects jsonb,
    bulletin_id integer,
    auto_generate_bulletin boolean DEFAULT true,
    notify_on_complete boolean DEFAULT true,
    grades_deadline timestamp without time zone,
    review_deadline timestamp without time zone,
    reminders_sent integer DEFAULT 0,
    last_reminder_sent timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.bulletins (
    id integer NOT NULL,
    student_id integer NOT NULL,
    teacher_id integer,
    class_id integer NOT NULL,
    school_id integer NOT NULL,
    term text NOT NULL,
    academic_year text NOT NULL,
    status text DEFAULT 'draft'::text NOT NULL,
    approved_at timestamp without time zone,
    sent_at timestamp without time zone,
    approved_by integer,
    sent_by integer,
    general_average numeric(5,2),
    class_rank integer,
    total_students_in_class integer,
    teacher_comments text,
    director_comments text,
    work_appreciation text,
    conduct_appreciation text,
    pdf_url text,
    digital_signature_hash text,
    qr_code text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.business_partners (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    sector character varying(100) NOT NULL,
    type character varying(50) NOT NULL,
    description text,
    address text,
    city character varying(100),
    region character varying(100),
    country character varying(100) DEFAULT 'Cameroun'::character varying,
    latitude numeric(10,8),
    longitude numeric(11,8),
    contact_person character varying(255),
    contact_position character varying(255),
    phone character varying(20),
    email character varying(255),
    website character varying(255),
    partnership_type character varying(50) NOT NULL,
    partnership_since character varying(10),
    status character varying(20) DEFAULT 'active'::character varying,
    rating numeric(3,2) DEFAULT 0.00,
    students_placed integer DEFAULT 0,
    opportunities_offered integer DEFAULT 0,
    programs jsonb,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.chat_conversations (
    id integer NOT NULL,
    participant_one_id integer NOT NULL,
    participant_one_role text NOT NULL,
    participant_two_id integer NOT NULL,
    participant_two_role text NOT NULL,
    student_id integer,
    school_id integer NOT NULL,
    last_message_at timestamp without time zone DEFAULT now(),
    last_message_preview text,
    participant_one_unread integer DEFAULT 0,
    participant_two_unread integer DEFAULT 0,
    status text DEFAULT 'active'::text,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.chat_messages (
    id integer NOT NULL,
    conversation_id integer NOT NULL,
    sender_id integer NOT NULL,
    sender_name text,
    sender_role text,
    content text NOT NULL,
    message_type text DEFAULT 'text'::text,
    attachment_url text,
    attachment_name text,
    is_read boolean DEFAULT false,
    read_at timestamp without time zone,
    is_edited boolean DEFAULT false,
    edited_at timestamp without time zone,
    is_deleted boolean DEFAULT false,
    deleted_at timestamp without time zone,
    reply_to_id integer,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.chat_typing_indicators (
    id integer NOT NULL,
    conversation_id integer NOT NULL,
    user_id integer NOT NULL,
    is_typing boolean DEFAULT false,
    last_typing_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.class_sessions (
    id integer NOT NULL,
    course_id integer,
    title text NOT NULL,
    description text,
    scheduled_start timestamp without time zone NOT NULL,
    scheduled_end timestamp without time zone,
    actual_start timestamp without time zone,
    actual_end timestamp without time zone,
    room_name text NOT NULL,
    room_password text,
    status text DEFAULT 'scheduled'::text NOT NULL,
    recording_url text,
    recording_size integer,
    max_duration integer DEFAULT 120,
    lobby_enabled boolean DEFAULT true,
    waiting_room_enabled boolean DEFAULT false,
    chat_enabled boolean DEFAULT true,
    screen_share_enabled boolean DEFAULT true,
    created_by integer NOT NULL,
    metadata text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    teacher_id integer NOT NULL,
    class_id integer,
    subject_id integer,
    creator_type character varying(50) DEFAULT 'school'::character varying,
    duration_minutes integer,
    notifications_sent boolean DEFAULT false,
    recurrence_id integer
);
CREATE TABLE public.classes (
    id integer NOT NULL,
    name text NOT NULL,
    level text,
    section text,
    school_id integer NOT NULL,
    teacher_id integer,
    academic_year_id integer NOT NULL,
    max_students integer DEFAULT 30,
    created_at timestamp without time zone DEFAULT now(),
    is_active boolean DEFAULT true,
    room text
);
CREATE TABLE public.communication_logs (
    id integer NOT NULL,
    sender_id integer NOT NULL,
    recipient_id integer NOT NULL,
    type text NOT NULL,
    subject text,
    message text NOT NULL,
    status text DEFAULT 'pending'::text,
    sent_at timestamp without time zone DEFAULT now(),
    delivered_at timestamp without time zone,
    metadata jsonb
);
CREATE TABLE public.competencies (
    id integer NOT NULL,
    school_id integer NOT NULL,
    subject_id integer,
    subject_name text,
    form_level text,
    competency_text_fr text NOT NULL,
    competency_text_en text,
    category text DEFAULT 'general'::text,
    domain_area text,
    display_order integer DEFAULT 1,
    is_active boolean DEFAULT true,
    created_by integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.competency_evaluation_systems (
    id integer NOT NULL,
    name text NOT NULL,
    language text NOT NULL,
    description text,
    is_active boolean DEFAULT true,
    levels jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.competency_templates (
    id integer NOT NULL,
    school_id integer,
    created_by integer NOT NULL,
    subject_name text NOT NULL,
    term text NOT NULL,
    class_level text,
    competencies_fr text NOT NULL,
    competencies_en text NOT NULL,
    learning_objectives jsonb,
    evaluation_criteria jsonb,
    is_active boolean DEFAULT true,
    is_global boolean DEFAULT false,
    usage_count integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.course_enrollments (
    id integer NOT NULL,
    course_id integer NOT NULL,
    user_id integer NOT NULL,
    role text NOT NULL,
    enrolled_at timestamp without time zone DEFAULT now(),
    is_active boolean DEFAULT true
);
CREATE TABLE public.daily_connections (
    id integer NOT NULL,
    user_id integer NOT NULL,
    user_email text NOT NULL,
    user_role text NOT NULL,
    user_name text NOT NULL,
    ip_address text NOT NULL,
    location jsonb,
    user_agent text,
    connection_date timestamp without time zone DEFAULT now(),
    session_id text,
    access_method text DEFAULT 'web'::text,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.device_location_history (
    id integer NOT NULL,
    device_id integer NOT NULL,
    latitude text,
    longitude text,
    accuracy text,
    "timestamp" timestamp without time zone DEFAULT now(),
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.educafric_number_counters (
    id integer NOT NULL,
    type text NOT NULL,
    current_counter integer DEFAULT 0 NOT NULL,
    last_generated text,
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.educafric_numbers (
    id integer NOT NULL,
    educafric_number text NOT NULL,
    type text NOT NULL,
    entity_type text NOT NULL,
    entity_id integer,
    status text DEFAULT 'active'::text NOT NULL,
    issued_by integer,
    notes text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.educational_content (
    id integer NOT NULL,
    title text NOT NULL,
    description text,
    type text DEFAULT 'lesson'::text,
    subject_id integer,
    level text,
    duration integer DEFAULT 60,
    objectives text,
    prerequisites text,
    teacher_id integer,
    school_id integer,
    files jsonb,
    status text DEFAULT 'draft'::text,
    visibility text DEFAULT 'school'::text,
    download_count integer DEFAULT 0,
    tags text[],
    is_shared boolean DEFAULT false,
    is_template boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    rating numeric(3,2),
    approved_by integer,
    approved_at timestamp without time zone,
    shared_with jsonb,
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.emergency_alerts (
    id integer NOT NULL,
    device_id integer NOT NULL,
    type text,
    alert_type text,
    message text,
    latitude text,
    longitude text,
    location jsonb,
    severity text,
    is_read boolean DEFAULT false,
    is_resolved boolean DEFAULT false,
    "timestamp" timestamp without time zone DEFAULT now(),
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.enrollments (
    id integer NOT NULL,
    student_id integer NOT NULL,
    class_id integer NOT NULL,
    academic_year_id integer NOT NULL,
    enrollment_date timestamp without time zone DEFAULT now(),
    status text DEFAULT 'active'::text
);
CREATE TABLE public.fee_audit_logs (
    id integer NOT NULL,
    school_id integer NOT NULL,
    actor_id integer NOT NULL,
    actor_role text,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id integer NOT NULL,
    previous_value jsonb,
    new_value jsonb,
    amount_before integer,
    amount_after integer,
    description text,
    ip_address text,
    user_agent text,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.fee_notification_queue (
    id integer NOT NULL,
    school_id integer NOT NULL,
    assigned_fee_id integer,
    student_id integer NOT NULL,
    parent_id integer,
    notification_type text NOT NULL,
    title text NOT NULL,
    message text NOT NULL,
    channels text[],
    email_sent boolean DEFAULT false,
    whatsapp_sent boolean DEFAULT false,
    pwa_sent boolean DEFAULT false,
    scheduled_for timestamp without time zone,
    sent_at timestamp without time zone,
    status text DEFAULT 'pending'::text,
    error_message text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.fee_receipts (
    id integer NOT NULL,
    school_id integer NOT NULL,
    payment_id integer NOT NULL,
    student_id integer NOT NULL,
    receipt_number text NOT NULL,
    total_amount integer NOT NULL,
    payment_method text,
    transaction_ref text,
    pdf_url text,
    status text DEFAULT 'generated'::text,
    sent_at timestamp without time zone,
    viewed_at timestamp without time zone,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.fee_structures (
    id integer NOT NULL,
    school_id integer NOT NULL,
    name text NOT NULL,
    name_fr text,
    name_en text,
    description text,
    fee_type text NOT NULL,
    amount integer NOT NULL,
    currency text DEFAULT 'XAF'::text,
    class_id integer,
    grade_level text,
    frequency text DEFAULT 'term'::text NOT NULL,
    term_id integer,
    academic_year_id integer,
    due_date timestamp without time zone,
    due_day_of_month integer,
    early_payment_discount integer DEFAULT 0,
    early_payment_days integer DEFAULT 0,
    sibling_discount integer DEFAULT 0,
    scholarship_eligible boolean DEFAULT true,
    is_active boolean DEFAULT true,
    is_mandatory boolean DEFAULT true,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.geofence_violations (
    id integer NOT NULL,
    device_id integer NOT NULL,
    violation_type text,
    location jsonb,
    "timestamp" timestamp without time zone DEFAULT now(),
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.geolocation_alerts (
    id integer NOT NULL,
    student_id integer NOT NULL,
    device_id integer,
    school_id integer NOT NULL,
    parent_id integer,
    alert_type text NOT NULL,
    priority text DEFAULT 'normal'::text NOT NULL,
    message text NOT NULL,
    latitude numeric(10,8),
    longitude numeric(11,8),
    safe_zone_id integer,
    is_resolved boolean DEFAULT false,
    resolved_by integer,
    resolved_at timestamp without time zone,
    notifications_sent jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.geolocation_devices (
    id integer NOT NULL,
    student_id integer NOT NULL,
    device_type text NOT NULL,
    device_id text NOT NULL,
    is_active boolean DEFAULT true,
    battery_level integer,
    last_update timestamp without time zone,
    emergency_mode boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.grade_review_history (
    id integer NOT NULL,
    grade_submission_id integer NOT NULL,
    reviewer_id integer NOT NULL,
    review_action text NOT NULL,
    previous_status text,
    new_status text NOT NULL,
    feedback text,
    return_reason text,
    previous_grade_data jsonb,
    new_grade_data jsonb,
    review_priority text,
    time_spent_reviewing integer,
    ip_address text,
    user_agent text,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.grades (
    id integer NOT NULL,
    student_id integer NOT NULL,
    subject_id integer NOT NULL,
    teacher_id integer NOT NULL,
    class_id integer NOT NULL,
    term_id integer NOT NULL,
    value numeric(5,2) NOT NULL,
    max_value numeric(5,2) DEFAULT 20.00,
    grade_type text NOT NULL,
    description text,
    date_recorded timestamp without time zone DEFAULT now(),
    published_to_parents boolean DEFAULT false
);
CREATE TABLE public.homework (
    id integer NOT NULL,
    title text NOT NULL,
    description text,
    subject_id integer NOT NULL,
    class_id integer NOT NULL,
    teacher_id integer NOT NULL,
    due_date timestamp without time zone NOT NULL,
    assigned_date timestamp without time zone DEFAULT now(),
    max_points numeric(5,2),
    is_published boolean DEFAULT false,
    reminder_enabled boolean DEFAULT true,
    reminder_days integer DEFAULT 1,
    reminder_sent_at timestamp without time zone,
    notify_students boolean DEFAULT true,
    notify_parents boolean DEFAULT true,
    school_id integer,
    instructions text,
    status text DEFAULT 'active'::text,
    priority text DEFAULT 'medium'::text,
    notify_channels jsonb,
    created_at timestamp without time zone DEFAULT now(),
    archived_at timestamp without time zone,
    archived_by integer,
    updated_at timestamp without time zone DEFAULT now(),
    is_active boolean DEFAULT true,
    attachments jsonb
);
CREATE TABLE public.homework_submissions (
    id integer NOT NULL,
    homework_id integer NOT NULL,
    student_id integer NOT NULL,
    submission_text text,
    attachment_url text,
    submitted_at timestamp without time zone DEFAULT now(),
    grade numeric(5,2),
    feedback text,
    teacher_graded_at timestamp without time zone,
    attachment_urls jsonb,
    submission_source text DEFAULT 'web'::text,
    status text DEFAULT 'pending'::text,
    score numeric(5,2),
    grade_by integer,
    graded_at timestamp without time zone,
    parent_notified boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.internships (
    id integer NOT NULL,
    student_id integer NOT NULL,
    partner_id integer NOT NULL,
    school_id integer NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    start_date character varying(10) NOT NULL,
    end_date character varying(10) NOT NULL,
    duration integer,
    status character varying(20) DEFAULT 'planned'::character varying,
    supervisor_name character varying(255),
    supervisor_email character varying(255),
    supervisor_phone character varying(20),
    student_rating numeric(3,2),
    company_rating numeric(3,2),
    student_feedback text,
    company_feedback text,
    completion_status character varying(20),
    job_offer_received boolean DEFAULT false,
    skills_acquired jsonb,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.library_books (
    id integer NOT NULL,
    title jsonb NOT NULL,
    author text NOT NULL,
    description jsonb,
    link_url text,
    cover_url text,
    subject_ids jsonb DEFAULT '[]'::jsonb,
    recommended_level text,
    department_ids jsonb DEFAULT '[]'::jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.library_recommendation_audience (
    id integer NOT NULL,
    recommendation_id integer NOT NULL,
    target_type text NOT NULL,
    target_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.library_recommendation_dispatch (
    id integer NOT NULL,
    recommendation_id integer NOT NULL,
    parent_id integer NOT NULL,
    channel text NOT NULL,
    status text DEFAULT 'queued'::text NOT NULL,
    error text,
    sent_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.library_recommendations (
    id integer NOT NULL,
    book_id integer NOT NULL,
    teacher_id integer NOT NULL,
    audience_type text NOT NULL,
    audience_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    note text,
    recommended_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.login_activity (
    id integer NOT NULL,
    user_id integer NOT NULL,
    user_email character varying(255),
    user_name character varying(255),
    user_role character varying(50),
    ip_address character varying(50),
    country character varying(100),
    city character varying(100),
    login_time timestamp without time zone DEFAULT now(),
    school_id integer,
    school_name character varying(255)
);
CREATE TABLE public.messages (
    id integer NOT NULL,
    sender_id integer NOT NULL,
    sender_name text,
    sender_role text,
    recipient_id integer NOT NULL,
    recipient_name text,
    recipient_role text,
    school_id integer,
    subject text,
    content text NOT NULL,
    message_type text,
    is_read boolean DEFAULT false,
    status text DEFAULT 'sent'::text,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.monthly_absence_reports (
    id integer NOT NULL,
    school_id integer NOT NULL,
    generated_by integer NOT NULL,
    report_month integer NOT NULL,
    report_year integer NOT NULL,
    academic_year text NOT NULL,
    total_absences integer DEFAULT 0,
    resolved_absences integer DEFAULT 0,
    unresolved_absences integer DEFAULT 0,
    average_resolution_time numeric(5,2),
    most_absent_teacher integer,
    most_common_reason text,
    total_affected_students integer DEFAULT 0,
    total_affected_classes integer DEFAULT 0,
    total_notifications_sent integer DEFAULT 0,
    substitute_success_rate numeric(5,2),
    report_data jsonb,
    report_file_url text,
    status text DEFAULT 'draft'::text,
    finalized_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.notification_preferences (
    id integer NOT NULL,
    user_id integer NOT NULL,
    push_notifications boolean DEFAULT true,
    email_notifications boolean DEFAULT true,
    sms_notifications boolean DEFAULT false,
    phone text,
    auto_open boolean DEFAULT true,
    sound_enabled boolean DEFAULT true,
    vibration_enabled boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.notifications (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    type text NOT NULL,
    title text NOT NULL,
    message text NOT NULL,
    priority text DEFAULT 'normal'::text,
    is_read boolean DEFAULT false,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now(),
    title_fr text,
    title_en text,
    message_fr text,
    message_en text
);
CREATE TABLE public.online_class_activations (
    id integer NOT NULL,
    activator_type text NOT NULL,
    activator_id integer NOT NULL,
    duration_type text NOT NULL,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    activated_by text NOT NULL,
    admin_user_id integer,
    payment_id text,
    payment_method text,
    amount_paid integer,
    notes text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.online_class_recurrences (
    id integer NOT NULL,
    school_id integer NOT NULL,
    course_id integer,
    teacher_id integer NOT NULL,
    class_id integer NOT NULL,
    subject_id integer,
    title text NOT NULL,
    description text,
    rule_type character varying(50) NOT NULL,
    "interval" integer DEFAULT 1,
    by_day text[] DEFAULT '{}'::text[],
    start_time character varying(10) NOT NULL,
    duration_minutes integer NOT NULL,
    start_date date NOT NULL,
    end_date date,
    is_active boolean DEFAULT true,
    paused_at timestamp without time zone,
    created_by integer NOT NULL,
    auto_notify boolean DEFAULT true,
    occurrences_generated integer DEFAULT 0,
    last_generated_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.online_class_usage_logs (
    id integer NOT NULL,
    activation_id integer NOT NULL,
    session_id integer NOT NULL,
    teacher_id integer NOT NULL,
    school_id integer,
    session_duration integer,
    participant_count integer,
    was_within_allowed_window boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.online_classes_subscriptions (
    id integer NOT NULL,
    school_id integer NOT NULL,
    is_active boolean DEFAULT false,
    plan text DEFAULT 'premium'::text,
    monthly_price integer DEFAULT 250000,
    currency text DEFAULT 'XAF'::text,
    activated_at timestamp without time zone,
    expires_at timestamp without time zone,
    auto_renew boolean DEFAULT true,
    stripe_subscription_id text,
    stripe_customer_id text,
    last_payment_at timestamp without time zone,
    next_payment_at timestamp without time zone,
    grace_period_ends timestamp without time zone,
    canceled_at timestamp without time zone,
    cancel_reason text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.online_courses (
    id integer NOT NULL,
    school_id integer,
    title text NOT NULL,
    description text,
    subject_id integer,
    class_id integer,
    teacher_id integer NOT NULL,
    language text DEFAULT 'fr'::text,
    is_active boolean DEFAULT true,
    max_participants integer DEFAULT 50,
    allow_recording boolean DEFAULT true,
    require_approval boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    is_independent boolean DEFAULT false
);
CREATE TABLE public.page_visits (
    id integer NOT NULL,
    user_id integer NOT NULL,
    user_email text NOT NULL,
    user_role text NOT NULL,
    page_path text NOT NULL,
    module_name text,
    dashboard_type text,
    time_spent integer,
    ip_address text NOT NULL,
    session_id text,
    visit_date timestamp without time zone DEFAULT now(),
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.parent_request_notifications (
    id integer NOT NULL,
    request_id integer NOT NULL,
    recipient_id integer NOT NULL,
    recipient_type text NOT NULL,
    channel text NOT NULL,
    message text NOT NULL,
    status text DEFAULT 'pending'::text,
    sent_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.parent_request_responses (
    id integer NOT NULL,
    request_id integer NOT NULL,
    responder_id integer NOT NULL,
    response text NOT NULL,
    response_type text NOT NULL,
    is_public boolean DEFAULT false,
    attachments text[],
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.parent_requests (
    id integer NOT NULL,
    parent_id integer NOT NULL,
    student_id integer NOT NULL,
    school_id integer NOT NULL,
    type text NOT NULL,
    category text NOT NULL,
    subject text NOT NULL,
    description text NOT NULL,
    priority text DEFAULT 'medium'::text,
    status text DEFAULT 'pending'::text,
    requested_date text,
    attachments text[],
    admin_response text,
    response_date timestamp without time zone,
    processed_by integer,
    notes text,
    is_urgent boolean DEFAULT false,
    requires_approval boolean DEFAULT true,
    notifications_sent boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    school_code text,
    child_first_name text,
    child_last_name text,
    child_date_of_birth text,
    relationship_type text,
    contact_phone text,
    response_message text,
    responded_at timestamp without time zone,
    responded_by integer
);
CREATE TABLE public.parent_student_relations (
    id integer NOT NULL,
    parent_id integer NOT NULL,
    student_id integer NOT NULL,
    relationship text NOT NULL,
    is_primary boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    status text DEFAULT 'approved'::text,
    requested_by text,
    verification_code text,
    approved_at timestamp without time zone
);
CREATE TABLE public.partnership_communications (
    id integer NOT NULL,
    agreement_id integer NOT NULL,
    sender_id integer NOT NULL,
    recipient_email character varying(255) NOT NULL,
    subject character varying(255) NOT NULL,
    message text NOT NULL,
    message_type character varying(50) DEFAULT 'general'::character varying,
    status character varying(20) DEFAULT 'sent'::character varying,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.payment_items (
    id integer NOT NULL,
    payment_id integer NOT NULL,
    assigned_fee_id integer NOT NULL,
    amount integer NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.payments (
    id integer NOT NULL,
    user_id integer NOT NULL,
    school_id integer,
    amount numeric(10,2) NOT NULL,
    currency text DEFAULT 'USD'::text,
    type text NOT NULL,
    status text NOT NULL,
    stripe_payment_intent_id text,
    stripe_subscription_id text,
    description text,
    paid_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.predefined_appreciations (
    id integer NOT NULL,
    school_id integer,
    created_by integer NOT NULL,
    name text NOT NULL,
    category text NOT NULL,
    target_role text NOT NULL,
    appreciation_fr text NOT NULL,
    appreciation_en text NOT NULL,
    subject_context text,
    competency_level text,
    grade_range jsonb,
    is_active boolean DEFAULT true,
    is_global boolean DEFAULT false,
    usage_count integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.pwa_analytics (
    id integer NOT NULL,
    user_id integer,
    session_id text NOT NULL,
    access_method text NOT NULL,
    device_type text,
    user_agent text,
    is_standalone boolean DEFAULT false,
    is_pwa_installed boolean DEFAULT false,
    push_permission_granted boolean DEFAULT false,
    session_duration integer,
    pages_visited integer DEFAULT 1,
    actions_performed integer DEFAULT 0,
    offline_time integer DEFAULT 0,
    ip_address text,
    country text,
    city text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.replacement_notifications (
    id integer NOT NULL,
    replacement_id integer NOT NULL,
    recipient_id integer NOT NULL,
    notification_type character varying(50) NOT NULL,
    channel character varying(50) NOT NULL,
    sent_at timestamp without time zone DEFAULT now(),
    status character varying(50) DEFAULT 'sent'::character varying
);
CREATE TABLE public.role_affiliations (
    id integer NOT NULL,
    user_id integer NOT NULL,
    role text NOT NULL,
    school_id integer,
    description text,
    status text DEFAULT 'active'::text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.rooms (
    id integer NOT NULL,
    name text NOT NULL,
    school_id integer NOT NULL,
    capacity integer,
    is_occupied boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    type text DEFAULT 'classroom'::text,
    building text,
    floor text,
    equipment text
);
CREATE TABLE public.safe_zones (
    id integer NOT NULL,
    school_id integer NOT NULL,
    parent_id integer,
    name text NOT NULL,
    description text,
    type text DEFAULT 'custom'::text,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    radius integer DEFAULT 100 NOT NULL,
    is_active boolean DEFAULT true,
    alert_on_entry boolean DEFAULT false,
    alert_on_exit boolean DEFAULT true,
    children_ids jsonb,
    schedule jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.school_levels (
    id integer NOT NULL,
    school_id integer NOT NULL,
    name text NOT NULL,
    name_fr text,
    name_en text,
    "order" integer NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.school_parent_pricing (
    id integer NOT NULL,
    school_id integer NOT NULL,
    communication_enabled boolean DEFAULT true,
    communication_price integer DEFAULT 5000,
    communication_period text DEFAULT 'annual'::text,
    geolocation_enabled boolean DEFAULT true,
    geolocation_price integer DEFAULT 5000,
    geolocation_period text DEFAULT 'annual'::text,
    discount_2_children integer DEFAULT 20,
    discount_3plus_children integer DEFAULT 40,
    updated_by integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.school_partnership_agreements (
    id integer NOT NULL,
    school_id integer NOT NULL,
    partner_id integer NOT NULL,
    agreement_type character varying(50) NOT NULL,
    start_date character varying(10),
    end_date character varying(10),
    status character varying(20) DEFAULT 'active'::character varying,
    terms text,
    contact_frequency character varying(20),
    last_contact_date character varying(10),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.schools (
    id integer NOT NULL,
    name text NOT NULL,
    type text NOT NULL,
    address text,
    phone text,
    email text,
    logo_url text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    school_logo_url text,
    logo_uploaded_at timestamp without time zone,
    academic_year text,
    current_term text,
    educafric_number text,
    educational_type text DEFAULT 'general'::text NOT NULL,
    term_start_date timestamp without time zone,
    term_end_date timestamp without time zone,
    settings jsonb,
    regionale_ministerielle text,
    delegation_departementale text,
    boite_postale text,
    arrondissement text,
    geolocation_enabled boolean DEFAULT false,
    pwa_enabled boolean DEFAULT true,
    whatsapp_enabled boolean DEFAULT false,
    sms_enabled boolean DEFAULT false,
    email_enabled boolean DEFAULT true,
    use_cba_format boolean DEFAULT false,
    website text,
    description text,
    established_year integer,
    principal_name text,
    student_capacity integer,
    is_sandbox boolean DEFAULT false NOT NULL,
    offline_premium_enabled boolean DEFAULT false NOT NULL,
    communications_enabled boolean DEFAULT true NOT NULL,
    educational_content_enabled boolean DEFAULT true NOT NULL,
    delegate_admins_enabled boolean DEFAULT true NOT NULL,
    canteen_enabled boolean DEFAULT true NOT NULL,
    school_bus_enabled boolean DEFAULT true NOT NULL,
    online_classes_enabled boolean DEFAULT true NOT NULL,
    slogan character varying(255),
    country_code text DEFAULT 'CM'::text NOT NULL,
    currency text DEFAULT 'XAF'::text
);
CREATE TABLE public.session (
    sid character varying NOT NULL,
    sess json NOT NULL,
    expire timestamp(6) without time zone NOT NULL
);
CREATE TABLE public.signatures (
    id integer NOT NULL,
    school_id integer,
    user_id integer,
    signature_type character varying(50) DEFAULT 'principal'::character varying NOT NULL,
    signature_data text NOT NULL,
    signatory_name character varying(255),
    signatory_title character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT true,
    user_role character varying(50) DEFAULT 'director'::character varying
);
CREATE TABLE public.subject_competency_assignments (
    id integer NOT NULL,
    school_id integer NOT NULL,
    subject_id integer NOT NULL,
    competency_id integer NOT NULL,
    form_level text NOT NULL,
    display_order integer DEFAULT 1,
    is_required boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.subjects (
    id integer NOT NULL,
    name_fr text NOT NULL,
    name_en text NOT NULL,
    code text NOT NULL,
    coefficient numeric(3,2) DEFAULT 1.00,
    school_id integer NOT NULL,
    class_id integer,
    bulletin_section text,
    subject_type text DEFAULT 'general'::text,
    name text,
    category text DEFAULT 'general'::text,
    hours_per_week integer DEFAULT 2,
    is_required boolean DEFAULT true
);
CREATE TABLE public.system_settings (
    id integer NOT NULL,
    school_id integer,
    key text NOT NULL,
    value text,
    type text DEFAULT 'string'::text,
    description text,
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.teacher_absence_actions (
    id integer NOT NULL,
    absence_id integer NOT NULL,
    action_type text NOT NULL,
    performed_by integer NOT NULL,
    action_details jsonb,
    target_audience text,
    notification_method text,
    message_template text,
    recipient_count integer DEFAULT 0,
    successful_deliveries integer DEFAULT 0,
    failed_deliveries integer DEFAULT 0,
    status text DEFAULT 'pending'::text,
    completed_at timestamp without time zone,
    error_message text,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.teacher_absence_notifications (
    id integer NOT NULL,
    absence_id integer NOT NULL,
    recipient_id integer NOT NULL,
    recipient_type text NOT NULL,
    channel text NOT NULL,
    status text DEFAULT 'pending'::text,
    sent_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.teacher_absences (
    id integer NOT NULL,
    teacher_id integer NOT NULL,
    school_id integer NOT NULL,
    class_id integer NOT NULL,
    subject_id integer NOT NULL,
    absence_date text NOT NULL,
    start_time text NOT NULL,
    end_time text NOT NULL,
    reason text NOT NULL,
    status text DEFAULT 'pending'::text,
    replacement_teacher_id integer,
    notes text,
    notifications_sent boolean DEFAULT false,
    created_by integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    urgency text DEFAULT 'medium'::text,
    contact_phone text,
    contact_email text,
    details text,
    classes_affected text[],
    end_date text
);
CREATE TABLE public.teacher_absences_enhanced (
    id integer NOT NULL,
    teacher_id integer NOT NULL,
    school_id integer NOT NULL,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    reason text NOT NULL,
    absence_type text NOT NULL,
    status text DEFAULT 'pending'::text,
    approved_by integer,
    approved_at timestamp without time zone,
    affected_classes jsonb,
    notifications_sent boolean DEFAULT false,
    notes text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.teacher_bulletin_preferences (
    id integer NOT NULL,
    teacher_id integer NOT NULL,
    student_id integer NOT NULL,
    class_id integer NOT NULL,
    school_id integer NOT NULL,
    term character varying(10) NOT NULL,
    academic_year character varying(20) NOT NULL,
    include_comments boolean DEFAULT true,
    include_rankings boolean DEFAULT true,
    include_statistics boolean DEFAULT true,
    include_performance_levels boolean DEFAULT false,
    include_first_trimester boolean DEFAULT false,
    include_discipline boolean DEFAULT false,
    include_student_work boolean DEFAULT false,
    include_class_profile boolean DEFAULT false,
    include_unjustified_absences boolean DEFAULT false,
    include_justified_absences boolean DEFAULT false,
    include_lateness boolean DEFAULT false,
    include_detentions boolean DEFAULT false,
    include_conduct_warning boolean DEFAULT false,
    include_conduct_blame boolean DEFAULT false,
    include_exclusions boolean DEFAULT false,
    include_permanent_exclusion boolean DEFAULT false,
    include_total_general boolean DEFAULT false,
    include_appreciations boolean DEFAULT false,
    include_general_average boolean DEFAULT false,
    include_trimester_average boolean DEFAULT false,
    include_number_of_averages boolean DEFAULT false,
    include_success_rate boolean DEFAULT false,
    include_coef boolean DEFAULT false,
    include_ctba boolean DEFAULT false,
    include_min_max boolean DEFAULT false,
    include_cba boolean DEFAULT false,
    include_ca boolean DEFAULT false,
    include_cma boolean DEFAULT false,
    include_cote boolean DEFAULT false,
    include_cna boolean DEFAULT false,
    include_work_appreciation boolean DEFAULT false,
    include_parent_visa boolean DEFAULT false,
    include_teacher_visa boolean DEFAULT false,
    include_headmaster_visa boolean DEFAULT false,
    include_class_council_decisions boolean DEFAULT false,
    include_class_council_mentions boolean DEFAULT false,
    include_orientation_recommendations boolean DEFAULT false,
    include_council_date boolean DEFAULT false,
    generation_format character varying(20) DEFAULT 'pdf'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.teacher_bulletins (
    id integer NOT NULL,
    teacher_id integer NOT NULL,
    school_id integer NOT NULL,
    student_id integer NOT NULL,
    class_id integer NOT NULL,
    term text NOT NULL,
    academic_year text NOT NULL,
    student_info jsonb NOT NULL,
    subjects jsonb NOT NULL,
    discipline jsonb NOT NULL,
    bulletin_type text,
    language text DEFAULT 'fr'::text,
    status text DEFAULT 'draft'::text NOT NULL,
    signed_at timestamp without time zone,
    signature_hash text,
    sent_to_school_at timestamp without time zone,
    reviewed_by integer,
    reviewed_at timestamp without time zone,
    review_status text,
    review_comments text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    is_third_trimester boolean DEFAULT false,
    annual_summary jsonb
);
CREATE TABLE public.teacher_grade_submissions (
    id integer NOT NULL,
    teacher_id integer NOT NULL,
    student_id integer NOT NULL,
    subject_id integer NOT NULL,
    class_id integer NOT NULL,
    school_id integer NOT NULL,
    term text NOT NULL,
    academic_year text NOT NULL,
    first_evaluation numeric(5,2),
    second_evaluation numeric(5,2),
    third_evaluation numeric(5,2),
    coefficient integer DEFAULT 1 NOT NULL,
    max_score numeric(5,2) DEFAULT 20.00,
    term_average numeric(5,2),
    weighted_score numeric(5,2),
    subject_comments text,
    student_rank integer,
    is_submitted boolean DEFAULT false,
    submitted_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    review_status text DEFAULT 'pending'::text NOT NULL,
    reviewed_by integer,
    reviewed_at timestamp without time zone,
    review_feedback text,
    return_reason text,
    review_priority text DEFAULT 'normal'::text,
    requires_attention boolean DEFAULT false,
    last_status_change timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.teacher_independent_activations (
    id integer NOT NULL,
    teacher_id integer NOT NULL,
    duration_type text DEFAULT 'yearly'::text NOT NULL,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    activated_by text NOT NULL,
    admin_user_id integer,
    payment_id text,
    payment_method text,
    amount_paid integer DEFAULT 25000,
    currency text DEFAULT 'XAF'::text,
    notes text,
    auto_renew boolean DEFAULT false,
    canceled_at timestamp without time zone,
    cancel_reason text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.teacher_independent_payments (
    id integer NOT NULL,
    teacher_id integer NOT NULL,
    student_id integer NOT NULL,
    parent_id integer,
    session_id integer,
    amount integer NOT NULL,
    currency text DEFAULT 'XAF'::text,
    payment_method text NOT NULL,
    payment_intent_id text,
    payment_status text DEFAULT 'pending'::text NOT NULL,
    period_start timestamp without time zone,
    period_end timestamp without time zone,
    notes text,
    receipt_url text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.teacher_independent_sessions (
    id integer NOT NULL,
    teacher_id integer NOT NULL,
    student_id integer NOT NULL,
    title text NOT NULL,
    description text,
    subject text NOT NULL,
    scheduled_start timestamp without time zone NOT NULL,
    scheduled_end timestamp without time zone NOT NULL,
    actual_start timestamp without time zone,
    actual_end timestamp without time zone,
    session_type text DEFAULT 'online'::text,
    location text,
    room_name text,
    room_password text,
    meeting_url text,
    status text DEFAULT 'scheduled'::text NOT NULL,
    cancel_reason text,
    teacher_notes text,
    student_feedback text,
    rating integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.teacher_independent_students (
    id integer NOT NULL,
    teacher_id integer NOT NULL,
    student_id integer NOT NULL,
    connection_date timestamp without time zone DEFAULT now(),
    connection_method text DEFAULT 'teacher_invite'::text,
    subjects text[],
    level text,
    objectives text,
    status text DEFAULT 'active'::text NOT NULL,
    ended_at timestamp without time zone,
    end_reason text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.teacher_notification_preferences (
    id integer NOT NULL,
    teacher_id integer NOT NULL,
    email_enabled boolean DEFAULT true,
    whatsapp_enabled boolean DEFAULT true,
    in_app_enabled boolean DEFAULT true,
    notify_on_approval boolean DEFAULT true,
    notify_on_return boolean DEFAULT true,
    notify_on_reminder boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.teacher_replacements (
    id integer NOT NULL,
    absence_id integer NOT NULL,
    school_id integer NOT NULL,
    original_teacher_id integer NOT NULL,
    replacement_teacher_id integer,
    class_id integer NOT NULL,
    subject_id integer NOT NULL,
    session_date timestamp without time zone NOT NULL,
    session_time text,
    status text DEFAULT 'pending'::text,
    assigned_by integer,
    assigned_at timestamp without time zone,
    confirmed_by integer,
    confirmed_at timestamp without time zone,
    completed_at timestamp without time zone,
    notes text,
    notifications_sent boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.teacher_student_invitations (
    id integer NOT NULL,
    teacher_id integer NOT NULL,
    target_type text NOT NULL,
    target_id integer NOT NULL,
    student_id integer,
    subjects text[],
    level text,
    message text,
    price_per_hour integer,
    price_per_session integer,
    currency text DEFAULT 'XAF'::text,
    status text DEFAULT 'pending'::text NOT NULL,
    response_message text,
    responded_at timestamp without time zone,
    expires_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.teacher_subject_assignments (
    id integer NOT NULL,
    school_id integer NOT NULL,
    teacher_id integer NOT NULL,
    class_id integer NOT NULL,
    subject_id integer NOT NULL,
    active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.terms (
    id integer NOT NULL,
    name text NOT NULL,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    academic_year_id integer NOT NULL,
    is_active boolean DEFAULT false
);
CREATE TABLE public.timetable_change_requests (
    id integer NOT NULL,
    teacher_id integer NOT NULL,
    school_id integer NOT NULL,
    timetable_id integer,
    change_type text NOT NULL,
    current_details jsonb,
    requested_details jsonb,
    reason text NOT NULL,
    urgency text DEFAULT 'normal'::text,
    status text DEFAULT 'pending'::text,
    admin_response text,
    responded_by integer,
    responded_at timestamp without time zone,
    is_read_by_teacher boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.timetable_notifications (
    id integer NOT NULL,
    teacher_id integer NOT NULL,
    timetable_id integer,
    change_type character varying(20) NOT NULL,
    message text NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    created_by integer,
    CONSTRAINT timetable_notifications_change_type_check CHECK (((change_type)::text = ANY ((ARRAY['created'::character varying, 'updated'::character varying, 'deleted'::character varying])::text[])))
);
CREATE TABLE public.timetable_slots (
    id integer NOT NULL,
    class_id integer NOT NULL,
    subject_id integer NOT NULL,
    teacher_id integer NOT NULL,
    day_of_week integer NOT NULL,
    start_time text NOT NULL,
    end_time text NOT NULL,
    room text,
    academic_year_id integer NOT NULL,
    is_active boolean DEFAULT true
);
CREATE TABLE public.timetables (
    id integer NOT NULL,
    school_id integer NOT NULL,
    teacher_id integer NOT NULL,
    class_id integer NOT NULL,
    subject_name character varying(255) NOT NULL,
    day_of_week integer NOT NULL,
    start_time character varying(8) NOT NULL,
    end_time character varying(8) NOT NULL,
    room character varying(255),
    academic_year character varying(20) NOT NULL,
    term character varying(10) NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    created_by integer,
    last_modified_by integer,
    notes text,
    CONSTRAINT timetables_day_of_week_check CHECK (((day_of_week >= 1) AND (day_of_week <= 7)))
);
CREATE TABLE public.tracking_devices (
    id integer NOT NULL,
    user_id integer NOT NULL,
    student_id integer,
    device_name text,
    device_type text,
    is_active boolean DEFAULT true,
    current_latitude text,
    current_longitude text,
    location_accuracy text,
    current_address text,
    last_location jsonb,
    battery_level integer,
    last_seen timestamp without time zone,
    tracking_settings jsonb,
    last_update timestamp without time zone,
    updated_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.tutorial_progress (
    id integer NOT NULL,
    user_id integer NOT NULL,
    current_step integer DEFAULT 0,
    completed boolean DEFAULT false,
    last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    tutorial_version text DEFAULT '1.0'::text NOT NULL,
    is_completed boolean DEFAULT false,
    total_steps integer DEFAULT 0,
    last_accessed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp without time zone,
    skipped_at timestamp without time zone,
    user_role text DEFAULT 'Student'::text NOT NULL,
    device_type text,
    completion_method text,
    session_data text,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.tutorial_steps (
    id integer NOT NULL,
    user_id integer NOT NULL,
    step_id character varying(255) NOT NULL,
    completed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    data jsonb DEFAULT '{}'::jsonb
);
CREATE TABLE public.user_achievements (
    id integer NOT NULL,
    user_id integer NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    date text NOT NULL,
    type text NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.users (
    id integer NOT NULL,
    email text,
    password text NOT NULL,
    role text NOT NULL,
    secondary_roles text[],
    first_name text NOT NULL,
    last_name text NOT NULL,
    gender text,
    phone text,
    school_id integer,
    stripe_customer_id text,
    stripe_subscription_id text,
    subscription_status text DEFAULT 'inactive'::text,
    two_factor_enabled boolean DEFAULT false,
    firebase_uid text,
    is_test_account boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    password_reset_token text,
    password_reset_expiry timestamp without time zone,
    last_login_at timestamp without time zone,
    profile_picture_url text,
    preferred_language character varying(2) DEFAULT 'en'::character varying,
    whatsapp_number character varying(20),
    photo_url text,
    two_factor_secret text,
    two_factor_backup_codes text[],
    two_factor_verified_at timestamp without time zone,
    stripe_payment_intent_id text,
    subscription_plan text DEFAULT 'free'::text,
    subscription_start timestamp without time zone DEFAULT now(),
    subscription_end timestamp without time zone,
    last_login timestamp without time zone,
    session_data jsonb DEFAULT '{}'::jsonb,
    active_role text,
    role_history text,
    deletion_requested text,
    deletion_requested_at text,
    deletion_approved_by text,
    deletion_approved_at text,
    is_pwa_user boolean DEFAULT false,
    last_pwa_access timestamp without time zone,
    pwa_install_date timestamp without time zone,
    access_method text DEFAULT 'web'::text,
    teacher_signature_url text,
    is_principal_teacher boolean DEFAULT false,
    principal_of_class_id integer,
    signature_required boolean DEFAULT false,
    signature_uploaded_at timestamp without time zone,
    delegated_permissions text[],
    delegated_by_user_id integer,
    delegation_level text,
    delegation_expiry timestamp without time zone,
    can_delegate boolean DEFAULT false,
    facebook_id text,
    date_of_birth character varying(255),
    place_of_birth character varying(255),
    educafric_number text,
    guardian text,
    parent_email text,
    parent_phone text,
    is_repeater boolean DEFAULT false,
    whatsapp_e164 character varying(20),
    wa_opt_in boolean DEFAULT false,
    wa_language character varying(2) DEFAULT 'fr'::character varying,
    preferred_channel text DEFAULT 'email'::text,
    work_mode text DEFAULT 'school'::text,
    bio text,
    "position" text,
    experience integer,
    years_in_position integer,
    profile_image text,
    qualifications text,
    languages text,
    is_active boolean DEFAULT true
);
CREATE TABLE public.wa_clicks (
    id integer NOT NULL,
    recipient_id integer NOT NULL,
    template_id text NOT NULL,
    campaign text,
    ip text,
    user_agent text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.webpush_subscriptions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    endpoint text NOT NULL,
    p256dh_key text NOT NULL,
    auth_key text NOT NULL,
    user_agent text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.whatsapp_conversations (
    id integer NOT NULL,
    phone_number text NOT NULL,
    user_id integer,
    user_role text,
    conversation_status text DEFAULT 'active'::text,
    last_message_at timestamp without time zone DEFAULT now(),
    message_count integer DEFAULT 0,
    is_bot boolean DEFAULT true,
    assigned_to integer,
    tags jsonb,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.whatsapp_faq_knowledge (
    id integer NOT NULL,
    question text NOT NULL,
    answer text NOT NULL,
    category text NOT NULL,
    keywords text[],
    language text DEFAULT 'fr'::text,
    priority integer DEFAULT 0,
    usage_count integer DEFAULT 0,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.whatsapp_messages (
    id integer NOT NULL,
    conversation_id integer NOT NULL,
    message_id text,
    direction text NOT NULL,
    from_number text NOT NULL,
    to_number text NOT NULL,
    message_type text DEFAULT 'text'::text,
    content text,
    media_url text,
    status text DEFAULT 'sent'::text,
    is_bot boolean DEFAULT true,
    intent text,
    intent_confidence integer,
    response_time integer,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.whatsapp_quick_replies (
    id integer NOT NULL,
    trigger text NOT NULL,
    response_text text NOT NULL,
    category text NOT NULL,
    language text DEFAULT 'fr'::text,
    include_actions jsonb,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.zone_status (
    id integer NOT NULL,
    device_id integer NOT NULL,
    zone_id integer NOT NULL,
    is_in_zone boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT now(),
    created_at timestamp without time zone DEFAULT now()
);
