// Educafric Footer Component - Bilingual Footer for all generated documents
// Appears at the bottom of bulletins, reports, and other official documents

interface EducafricFooterProps {
  language?: 'fr' | 'en';
  className?: string;
}

export function EducafricFooter({ language = 'fr', className = '' }: EducafricFooterProps) {
  const content = {
    fr: {
      generatedBy: "Document réalisé par",
      platform: "EDUCAFRIC",
      tagline: "Plateforme Éducative Digitale pour l'Afrique",
      contact: "Contacts",
      phone: "Tél",
      email: "Email",
      website: "Site web",
      followUs: "Suivez-nous"
    },
    en: {
      generatedBy: "Document generated by",
      platform: "EDUCAFRIC",
      tagline: "Digital Educational Platform for Africa",
      contact: "Contact",
      phone: "Tel",
      email: "Email",
      website: "Website",
      followUs: "Follow us"
    }
  };

  const text = content[language];

  return (
    <div className={`mt-6 pt-4 border-t-2 border-gray-300 print:border-black ${className}`}>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-center">
        {/* Left: Platform Info */}
        <div className="space-y-1">
          <p className="text-xs text-gray-600 print:text-black">
            {text.generatedBy}
          </p>
          <p className="text-lg font-bold text-blue-600 print:text-black">
            🎓 {text.platform}
          </p>
          <p className="text-xs text-gray-500 print:text-black italic">
            {text.tagline}
          </p>
        </div>

        {/* Center: Contact Info */}
        <div className="space-y-1 text-sm">
          <p className="font-semibold text-gray-700 print:text-black">{text.contact}</p>
          <p className="text-xs">
            📞 {text.phone}: <span className="font-medium">+237 656 200 472</span>
          </p>
          <p className="text-xs">
            ✉️ {text.email}: <span className="font-medium">contact@educafric.com</span>
          </p>
          <p className="text-xs">
            🌐 {text.website}: <span className="font-medium text-blue-600 print:text-black">www.educafric.com</span>
          </p>
        </div>

        {/* Right: Social Media / Call to Action */}
        <div className="space-y-1">
          <p className="text-xs font-semibold text-gray-700 print:text-black">{text.followUs}</p>
          <div className="flex justify-center gap-3 text-xl">
            <span className="print:hidden">📱</span>
            <span className="print:hidden">💻</span>
            <span className="print:hidden">📧</span>
          </div>
          <p className="text-xs text-gray-500 print:text-black mt-2">
            {language === 'fr' 
              ? "Simplifiez la gestion scolaire avec Educafric" 
              : "Simplify school management with Educafric"}
          </p>
        </div>
      </div>

      {/* Bottom Bar */}
      <div className="mt-3 pt-2 border-t border-gray-200 print:border-gray-400">
        <p className="text-center text-xs text-gray-400 print:text-gray-600">
          © {new Date().getFullYear()} Educafric.com - {language === 'fr' ? 'Tous droits réservés' : 'All rights reserved'}
        </p>
      </div>
    </div>
  );
}

// Compact version for space-constrained documents
export function EducafricFooterCompact({ language = 'fr', className = '' }: EducafricFooterProps) {
  return (
    <div className={`mt-3 pt-2 border-t border-gray-300 print:border-black ${className}`}>
      <div className="flex flex-wrap justify-between items-center text-xs gap-2">
        <div className="font-medium text-blue-600 print:text-black">
          🎓 EDUCAFRIC.COM
        </div>
        <div className="text-gray-600 print:text-black">
          📞 +237 656 200 472 | ✉️ contact@educafric.com
        </div>
        <div className="text-gray-400 print:text-gray-600">
          {language === 'fr' ? 'Plateforme Éducative Digitale' : 'Digital Educational Platform'}
        </div>
      </div>
    </div>
  );
}
