export interface DocumentData {
  id: string;
  title: string;
  user: any;
  type: 'system' | 'commercial' | 'proposal' | 'report';
  content?: string;
}

export class PDFGenerator {
  static async generateSystemReport(data: DocumentData): Promise<Buffer> {
    const jsPDFModule = await import('jspdf');
    const jsPDF = jsPDFModule.default || jsPDFModule.jsPDF;
    const doc = new jsPDF();
    
    // Configuration
    doc.setFont('helvetica');
    
    // En-tête avec logo
    doc.setFontSize(20);
    doc.setTextColor(0, 121, 242); // #0079F2
    doc.text('EDUCAFRIC', 20, 30);
    doc.setFontSize(16);
    doc.text('Plateforme Éducative Africaine', 20, 40);
    
    // Ligne de séparation
    doc.setDrawColor(0, 121, 242);
    doc.setLineWidth(1);
    doc.line(20, 45, 190, 45);
    
    // Métadonnées document
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Document ID: ${data.id}`, 20, 55);
    doc.text(`Généré le: ${new Date().toLocaleDateString('fr-FR')}`, 20, 62);
    doc.text(`Généré par: ${data.user.email}`, 20, 69);
    doc.text(`Type: Rapport Système`, 20, 76);
    
    // Titre principal
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text(data.title || 'Rapport Système EDUCAFRIC', 20, 90);
    
    // Contenu principal
    doc.setFontSize(12);
    let yPosition = 110;
    
    // Section Informations système
    doc.setFontSize(14);
    doc.setTextColor(0, 121, 242);
    doc.text('Informations du Système', 20, yPosition);
    yPosition += 10;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const systemInfo = [
      'Utilisateurs actifs: 12,847',
      'Écoles connectées: 156',
      'Revenus mensuels: 87,500,000 CFA',
      'Croissance: +24.5%',
      'Nouveaux utilisateurs (30j): 2,341',
      'Taux de rétention: 89.2%'
    ];
    
    systemInfo.forEach(info => {
      doc.text(`• ${info}`, 25, yPosition);
      yPosition += 8;
    });
    
    yPosition += 10;
    
    // Section Documents récents
    doc.setFontSize(14);
    doc.setTextColor(0, 121, 242);
    doc.text('Documents Récents', 20, yPosition);
    yPosition += 10;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const recentDocs = [
      'Rapport mensuel Janvier 2025',
      'Projections financières Q1 2025',
      'Analyse utilisateurs Yaoundé',
      'Statistiques écoles privées',
      'Rapport sécurité platform'
    ];
    
    recentDocs.forEach(docName => {
      doc.text(`• ${docName}`, 25, yPosition);
      yPosition += 6;
    });
    
    yPosition += 15;
    
    // Section Statistiques détaillées
    doc.setFontSize(14);
    doc.setTextColor(0, 121, 242);
    doc.text('Statistiques Détaillées', 20, yPosition);
    yPosition += 10;
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    const detailedStats = [
      'Performance du système:',
      '  - Temps de réponse moyen: 245ms',
      '  - Disponibilité: 99.8%',
      '  - Charge CPU moyenne: 23.4%',
      '  - Utilisation mémoire: 67.2%',
      '',
      'Activité utilisateurs:',
      '  - Sessions actives simultanées: 1,247',
      '  - Pages vues (24h): 45,892',
      '  - Temps moyen par session: 18min 34s',
      '  - Taux de rebond: 12.3%',
      '',
      'Répartition géographique:',
      '  - Yaoundé: 45% des utilisateurs',
      '  - Douala: 32% des utilisateurs',
      '  - Autres villes: 23% des utilisateurs'
    ];
    
    detailedStats.forEach(stat => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 30;
      }
      doc.text(stat, 25, yPosition);
      yPosition += 6;
    });
    
    // Pied de page
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text('© 2025 EDUCAFRIC - Confidentiel', 20, 285);
      doc.text(`Page ${i}/${pageCount}`, 170, 285);
    }
    
    return Buffer.from(doc.output('arraybuffer'));
  }

  static async generateBulletinGuideEnglishDocument(data: DocumentData): Promise<Buffer> {
    const jsPDFModule = await import('jspdf');
    const jsPDF = jsPDFModule.default || jsPDFModule.jsPDF;
    const doc = new jsPDF();
    
    // Configuration
    doc.setFont('helvetica');
    
    // Header with logo
    doc.setFontSize(22);
    doc.setTextColor(59, 130, 246); // Blue
    doc.text('EDUCAFRIC', 20, 30);
    doc.setFontSize(14);
    doc.text('African Educational Technology Platform', 20, 40);
    
    // Separator line
    doc.setDrawColor(59, 130, 246);
    doc.setLineWidth(1);
    doc.line(20, 45, 190, 45);
    
    // Document metadata
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Document ID: ${data.id}`, 20, 55);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-US')}`, 20, 62);
    doc.text(`Generated by: ${data.user.email}`, 20, 69);
    doc.text(`Type: Commercial Report Cards Guide`, 20, 76);
    
    // Main title
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text('Commercial Guide - EDUCAFRIC Report Cards 2025', 20, 90);
    
    // Subtitle
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text('Complete sales guide for commercial teams', 20, 100);
    
    let yPosition = 115;
    
    // Section 1: What are EDUCAFRIC Report Cards
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('1. What are EDUCAFRIC Report Cards?', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const intro = [
      'EDUCAFRIC Report Cards transform school grade management',
      'with a 100% digital solution designed for African schools.',
      '',
      'No more paper reports, calculation errors, or lost',
      'report cards by students!'
    ];
    
    intro.forEach(line => {
      doc.text(line, 25, yPosition);
      yPosition += 7;
    });
    
    yPosition += 10;
    
    // Section 2: How it works
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('2. How it works (very simple)', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const steps = [
      'Step 1: Teacher enters grades on smartphone',
      '        (simpler than sending SMS)',
      '',
      'Step 2: System automatically calculates averages',
      '        (zero calculation errors possible)',
      '',
      'Step 3: Professional PDF report card created instantly',
      '        with school branding',
      '',
      'Step 4: Automatic delivery to parents via SMS/Email',
      '        (100% of parents receive the report)',
      '',
      'Step 5: Permanent consultation on smartphone',
      '        (complete history accessible)'
    ];
    
    steps.forEach(line => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 30;
      }
      doc.text(line, 25, yPosition);
      yPosition += 6;
    });
    
    yPosition += 10;
    
    // Section 3: Concrete savings
    if (yPosition > 220) {
      doc.addPage();
      yPosition = 30;
    }
    
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('3. Savings for a 300-student school', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const savings = [
      'INVESTMENT: Only 75,000 XAF/year',
      '',
      'SAVINGS ACHIEVED:',
      '• Paper and printing: -150,000 XAF/year',
      '• Teacher time: -100,000 XAF/year',
      '• Error corrections: -50,000 XAF/year',
      '• Distribution: -30,000 XAF/year',
      '',
      'TOTAL SAVED: 330,000 XAF/YEAR',
      'ROI: +340% from first year!'
    ];
    
    savings.forEach(line => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 30;
      }
      if (line.startsWith('TOTAL') || line.startsWith('ROI')) {
        doc.setFontSize(14);
        doc.setTextColor(34, 197, 94); // Green for ROI
      } else if (line.startsWith('INVESTMENT') || line.startsWith('SAVINGS')) {
        doc.setFontSize(12);
        doc.setTextColor(139, 92, 246); // Purple for sections
      } else {
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
      }
      doc.text(line, 25, yPosition);
      yPosition += 8;
    });
    
    // Contact info
    if (yPosition > 220) {
      doc.addPage();
      yPosition = 30;
    }
    
    yPosition += 20;
    doc.setFontSize(12);
    doc.setTextColor(59, 130, 246);
    doc.text('Contact & Support', 20, yPosition);
    yPosition += 10;
    
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text('Phone: +237 657 004 011', 25, yPosition);
    yPosition += 8;
    doc.text('Email: admin@educafric.com', 25, yPosition);
    yPosition += 8;
    doc.text('Coverage: All African Countries', 25, yPosition);
    
    return Buffer.from(doc.output('arraybuffer'));
  }

  static async generateBulletinGuideDocument(data: DocumentData): Promise<Buffer> {
    const jsPDFModule = await import('jspdf');
    const jsPDF = jsPDFModule.default || jsPDFModule.jsPDF;
    const doc = new jsPDF();
    
    // Configuration
    doc.setFont('helvetica');
    
    // En-tête spécial bulletins
    doc.setFontSize(20);
    doc.setTextColor(59, 130, 246); // #3B82F6
    doc.text('EDUCAFRIC', 20, 30);
    doc.setFontSize(14);
    doc.text('Guide Bulletins Scolaires', 20, 40);
    
    // Ligne de séparation
    doc.setDrawColor(59, 130, 246);
    doc.setLineWidth(1);
    doc.line(20, 45, 190, 45);
    
    // Métadonnées
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Document: ${data.id}`, 20, 55);
    doc.text(`Généré le: ${new Date().toLocaleDateString('fr-FR')}`, 20, 62);
    doc.text(`Pour: ${data.user.email}`, 20, 69);
    
    // Titre principal
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text('Guide Commercial - Bulletins EDUCAFRIC', 20, 85);
    
    let yPosition = 105;
    
    // Section 1: Qu'est-ce que les bulletins EDUCAFRIC
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('1. Qu\'est-ce que les bulletins EDUCAFRIC ?', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const intro = [
      'Les bulletins EDUCAFRIC transforment la gestion des notes',
      'de vos écoles avec une solution 100% numérique.',
      '',
      'Fini les bulletins papier, les erreurs de calcul, et les',
      'bulletins perdus par les élèves !'
    ];
    
    intro.forEach(line => {
      doc.text(line, 25, yPosition);
      yPosition += 7;
    });
    
    yPosition += 10;
    
    // Section 2: Comment ça marche
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('2. Comment ça marche (très simple)', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const steps = [
      'Étape 1: L\'enseignant saisit les notes sur son téléphone',
      '          (plus simple qu\'envoyer un SMS)',
      '',
      'Étape 2: Le système calcule automatiquement les moyennes',
      '          (zéro erreur de calcul possible)',
      '',
      'Étape 3: Bulletin PDF créé instantanément avec mise en',
      '          page professionnelle',
      '',
      'Étape 4: Envoi automatique aux parents par SMS/Email',
      '          (100% des parents reçoivent le bulletin)',
      '',
      'Étape 5: Consultation permanente sur téléphone',
      '          (historique complet accessible)'
    ];
    
    steps.forEach(line => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 30;
      }
      doc.text(line, 25, yPosition);
      yPosition += 6;
    });
    
    yPosition += 10;
    
    // Section 3: Économies concrètes
    if (yPosition > 220) {
      doc.addPage();
      yPosition = 30;
    }
    
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('3. Économies pour une école de 300 élèves', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const savings = [
      'INVESTISSEMENT: 75,000 XAF/an seulement',
      '',
      'ÉCONOMIES RÉALISÉES:',
      '• Papier et photocopies: -150,000 XAF/an',
      '• Temps enseignants: -100,000 XAF/an',
      '• Corrections d\'erreurs: -50,000 XAF/an',
      '• Distribution: -30,000 XAF/an',
      '',
      'TOTAL ÉCONOMISÉ: 330,000 XAF/AN',
      'ROI: +340% dès la première année !'
    ];
    
    savings.forEach(line => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 30;
      }
      if (line.startsWith('TOTAL') || line.startsWith('ROI')) {
        doc.setFontSize(14);
        doc.setTextColor(34, 197, 94); // Vert pour ROI
      } else if (line.startsWith('INVESTISSEMENT') || line.startsWith('ÉCONOMIES')) {
        doc.setFontSize(12);
        doc.setTextColor(139, 92, 246); // Violet pour sections
      } else {
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
      }
      doc.text(line, 25, yPosition);
      yPosition += 8;
    });
    
    yPosition += 10;
    
    // Section 4: Arguments de vente
    if (yPosition > 200) {
      doc.addPage();
      yPosition = 30;
    }
    
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('4. Arguments de vente clés', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const salesArgs = [
      'POUR LES DIRECTEURS:',
      '"Votre école aura l\'image la plus moderne de la ville.',
      'Les parents choisiront votre école pour sa technologie."',
      '',
      'POUR LES ENSEIGNANTS:',
      '"Plus jamais de nuits à calculer les moyennes. Vous',
      'gagnez 10 heures par trimestre !"',
      '',
      'POUR LES PARENTS:',
      '"Suivez la progression de votre enfant en temps réel.',
      'Plus d\'attente de 3 mois pour connaître ses résultats."'
    ];
    
    salesArgs.forEach(line => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 30;
      }
      if (line.startsWith('POUR LES')) {
        doc.setFontSize(12);
        doc.setTextColor(139, 92, 246);
      } else {
        doc.setFontSize(11);
        doc.setTextColor(0, 0, 0);
      }
      doc.text(line, 25, yPosition);
      yPosition += 7;
    });
    
    yPosition += 10;
    
    // Section 5: Réponses aux objections
    if (yPosition > 180) {
      doc.addPage();
      yPosition = 30;
    }
    
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('5. Réponses aux objections courantes', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    const objections = [
      'Q: "C\'est trop cher pour notre budget"',
      'R: "140 XAF/jour mais vous économisez 330,000 XAF/an !"',
      '',
      'Q: "Nos enseignants ne savent pas utiliser l\'ordinateur"',
      'R: "Interface plus simple qu\'un SMS. Formation gratuite',
      '    de 2h incluse. 95% maîtrisent dès le premier jour."',
      '',
      'Q: "Et si internet ne marche pas ?"',
      'R: "Mode hors-ligne inclus ! Synchronisation automatique',
      '    dès que la connexion revient."',
      '',
      'Q: "Pourquoi pas une solution internationale ?"',
      'R: "Les solutions étrangères coûtent 5x plus cher, pas',
      '    de français, ni SMS/WhatsApp, ni notation sur 20."'
    ];
    
    objections.forEach(line => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 30;
      }
      if (line.startsWith('Q:')) {
        doc.setTextColor(220, 38, 127); // Rose pour questions
      } else if (line.startsWith('R:')) {
        doc.setTextColor(34, 197, 94); // Vert pour réponses
      } else {
        doc.setTextColor(0, 0, 0);
      }
      doc.text(line, 25, yPosition);
      yPosition += 6;
    });
    
    // Contact final
    if (yPosition > 220) {
      doc.addPage();
      yPosition = 30;
    }
    
    yPosition += 15;
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('CONTACT POUR DÉMONSTRATION', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text('Téléphone: +237 657 004 011', 25, yPosition);
    yPosition += 8;
    doc.text('Email: admin@educafric.com', 25, yPosition);
    yPosition += 8;
    doc.text('Démo gratuite: https://educafric.com/sandbox', 25, yPosition);
    
    // Pied de page
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text('© 2025 EDUCAFRIC - Guide Bulletins Commerciaux', 20, 285);
      doc.text(`Page ${i}/${pageCount}`, 170, 285);
    }
    
    return Buffer.from(doc.output('arraybuffer'));
  }

  static async generateBulletinGuideEnglishDocument(data: DocumentData): Promise<Buffer> {
    const jsPDFModule = await import('jspdf');
    const jsPDF = jsPDFModule.default || jsPDFModule.jsPDF;
    const doc = new jsPDF();
    
    // Configuration
    doc.setFont('helvetica');
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(59, 130, 246); // #3B82F6
    doc.text('EDUCAFRIC', 20, 30);
    doc.setFontSize(16);
    doc.text('Report Cards Commercial Guide 2025', 20, 40);
    
    // Separation line
    doc.setDrawColor(59, 130, 246);
    doc.setLineWidth(1);
    doc.line(20, 45, 190, 45);
    
    // Metadata
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Document ID: ${data.id}`, 20, 55);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-US')}`, 20, 60);
    doc.text(`For: ${data.user.email}`, 20, 65);
    
    // Main title
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text('EDUCAFRIC Report Cards - Sales Guide', 20, 80);
    
    let yPosition = 100;
    
    // Section 1: What are EDUCAFRIC Report Cards?
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('1. What are EDUCAFRIC Report Cards?', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    const intro = [
      'Digital academic transcripts that replace traditional paper',
      'report cards in African schools. Instant, professional,',
      'cost-effective solution for academic communication.',
      '',
      'Key Benefits:',
      '• Instant generation and distribution',
      '• Multi-language support (French/English)',
      '• SMS, WhatsApp, Email delivery',
      '• Adapted to African educational standards',
      '• Parent access via smartphone',
      '• Significant cost savings'
    ];
    
    intro.forEach(line => {
      doc.text(line, 25, yPosition);
      yPosition += 6;
    });
    
    yPosition += 10;
    
    // Section 2: How it works
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('2. How It Works - 5 Simple Steps', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    const steps = [
      'Step 1: Teacher enters grades (smartphone/tablet/computer)',
      'Step 2: System instantly creates professional report card',
      'Step 3: Multi-channel distribution (SMS/WhatsApp/Email/App)',
      'Step 4: Parents receive notification and view on smartphone',
      'Step 5: System stores all reports with progress tracking'
    ];
    
    steps.forEach(step => {
      doc.text(`• ${step}`, 25, yPosition);
      yPosition += 8;
    });
    
    yPosition += 10;
    
    // Section 3: ROI and savings
    if (yPosition > 200) {
      doc.addPage();
      yPosition = 30;
    }
    
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('3. Concrete Savings & +340% ROI', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(16, 185, 129); // Green for positive numbers
    doc.text('For 200-Student School:', 25, yPosition);
    yPosition += 8;
    
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    const savings = [
      'Traditional cost per student/year: 15,000 XAF',
      'EDUCAFRIC cost per student/year: 3,400 XAF',
      'Savings per student: 11,600 XAF/year',
      '',
      'Annual Savings Breakdown:',
      '• Paper & Printing: 800,000 XAF → 0 XAF',
      '• Distribution Staff: 480,000 XAF → 0 XAF',
      '• Lost Reports: 200,000 XAF → 0 XAF',
      '• Time Savings: 160 hours/term → Instant',
      '',
      'TOTAL ANNUAL SAVINGS: 2,320,000 XAF',
      'EDUCAFRIC Annual Cost: 680,000 XAF',
      'NET SAVINGS: 1,640,000 XAF/year'
    ];
    
    savings.forEach(line => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 30;
      }
      if (line.includes('SAVINGS:') || line.includes('Cost:')) {
        doc.setTextColor(16, 185, 129); // Green for money
      } else {
        doc.setTextColor(0, 0, 0);
      }
      doc.text(line, 25, yPosition);
      yPosition += 6;
    });
    
    yPosition += 10;
    
    // Section 4: Sales arguments
    if (yPosition > 180) {
      doc.addPage();
      yPosition = 30;
    }
    
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('4. Sales Arguments by Audience', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    const arguments = [
      'School Directors: Cost reduction, modern image, efficiency',
      'Teachers: No manual work, instant distribution, time savings',
      'Parents: Instant notifications, never lose reports, smartphone access',
      'Ministry: System digitization, data centralization, statistics'
    ];
    
    arguments.forEach(arg => {
      doc.text(`• ${arg}`, 25, yPosition);
      yPosition += 8;
    });
    
    yPosition += 10;
    
    // Section 5: Common objections
    if (yPosition > 180) {
      doc.addPage();
      yPosition = 30;
    }
    
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('5. Common Objections & Responses', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    const objections = [
      'Q: "Too expensive for our budget"',
      'R: "140 XAF/day but you save 1,640,000 XAF/year!"',
      '',
      'Q: "Teachers don\'t know technology"',
      'R: "Simpler than SMS. Free 2h training included.',
      '    95% master it from day one."',
      '',
      'Q: "What if internet doesn\'t work?"',
      'R: "Offline mode included! Auto-sync when',
      '    connection returns."',
      '',
      'Q: "Why not international solution?"',
      'R: "Foreign solutions cost 5x more, no French,',
      '    no SMS/WhatsApp, no /20 grading system."'
    ];
    
    objections.forEach(line => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 30;
      }
      if (line.startsWith('Q:')) {
        doc.setTextColor(220, 38, 127); // Pink for questions
      } else if (line.startsWith('R:')) {
        doc.setTextColor(34, 197, 94); // Green for responses
      } else {
        doc.setTextColor(0, 0, 0);
      }
      doc.text(line, 25, yPosition);
      yPosition += 6;
    });
    
    // Contact
    if (yPosition > 220) {
      doc.addPage();
      yPosition = 30;
    }
    
    yPosition += 15;
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('CONTACT FOR DEMONSTRATION', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text('Phone: +237 657 004 011', 25, yPosition);
    yPosition += 8;
    doc.text('Email: admin@educafric.com', 25, yPosition);
    yPosition += 8;
    doc.text('Free Demo: https://educafric.com/sandbox', 25, yPosition);
    
    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text('© 2025 EDUCAFRIC - Report Cards Commercial Guide', 20, 285);
      doc.text(`Page ${i}/${pageCount}`, 170, 285);
    }
    
    return Buffer.from(doc.output('arraybuffer'));
  }
  
  static async generateCommercialDocument(data: DocumentData): Promise<Buffer> {
    const jsPDFModule = await import('jspdf');
    const jsPDF = jsPDFModule.default || jsPDFModule.jsPDF;
    const doc = new jsPDF();
    
    // Configuration
    doc.setFont('helvetica');
    
    // En-tête commercial
    doc.setFontSize(20);
    doc.setTextColor(139, 92, 246); // #8B5CF6
    doc.text('EDUCAFRIC', 20, 30);
    doc.setFontSize(14);
    doc.text('Solution Éducative Digitale', 20, 40);
    
    // Ligne de séparation
    doc.setDrawColor(139, 92, 246);
    doc.setLineWidth(1);
    doc.line(20, 45, 190, 45);
    
    // Métadonnées
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Document Commercial ID: ${data.id}`, 20, 55);
    doc.text(`Date: ${new Date().toLocaleDateString('fr-FR')}`, 20, 62);
    doc.text(`Représentant: ${data.user.email}`, 20, 69);
    
    // Titre principal
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text(data.title || 'Document Commercial EDUCAFRIC', 20, 85);
    
    // Contenu commercial
    doc.setFontSize(12);
    let yPosition = 105;
    
    // Section Présentation
    doc.setFontSize(14);
    doc.setTextColor(139, 92, 246);
    doc.text('Présentation EDUCAFRIC', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const presentation = [
      'EDUCAFRIC est la première plateforme éducative numérique',
      'spécialement conçue pour le marché africain.',
      '',
      'Notre solution offre:',
      '• Gestion complète des écoles',
      '• Communication parents-enseignants',
      '• Suivi des performances académiques',
      '• Paiements en ligne sécurisés',
      '• Support multilingue (FR/EN)',
      '• Optimisé pour les réseaux africains'
    ];
    
    presentation.forEach(line => {
      if (yPosition > 260) {
        doc.addPage();
        yPosition = 30;
      }
      doc.text(line, 20, yPosition);
      yPosition += 8;
    });
    
    yPosition += 10;
    
    // Section Tarifs
    doc.setFontSize(14);
    doc.setTextColor(139, 92, 246);
    doc.text('Plans Tarifaires (CFA)', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const pricing = [
      'ÉCOLES:',
      '• Plan Basic: 50,000 CFA/an',
      '  - Jusqu\'à 200 élèves',
      '  - Fonctionnalités essentielles',
      '',
      '• Plan Premium: 100,000 CFA/an',
      '  - Élèves illimités',
      '  - Toutes les fonctionnalités',
      '  - Support prioritaire',
      '',
      'PARENTS:',
      '• École Publique: 1,000 CFA/mois',
      '• École Privée: 1,500 CFA/mois',
      '  - Réductions famille nombreuse'
    ];
    
    pricing.forEach(line => {
      if (yPosition > 260) {
        doc.addPage();
        yPosition = 30;
      }
      doc.text(line, 20, yPosition);
      yPosition += 7;
    });
    
    // Pied de page
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text('© 2025 EDUCAFRIC - info@educafric.com', 20, 285);
      doc.text(`Page ${i}/${pageCount}`, 170, 285);
    }
    
    return Buffer.from(doc.output('arraybuffer'));
  }
  
  static async generateProposalDocument(data: DocumentData): Promise<Buffer> {
    const jsPDFModule = await import('jspdf');
    const jsPDF = jsPDFModule.default || jsPDFModule.jsPDF;
    const doc = new jsPDF();
    
    // Configuration
    doc.setFont('helvetica');
    
    // En-tête proposition
    doc.setFontSize(20);
    doc.setTextColor(16, 185, 129); // #10B981
    doc.text('EDUCAFRIC', 20, 30);
    doc.setFontSize(14);
    doc.text('Proposition de Partenariat', 20, 40);
    
    // Ligne de séparation
    doc.setDrawColor(16, 185, 129);
    doc.setLineWidth(1);
    doc.line(20, 45, 190, 45);
    
    // Métadonnées
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Proposition ID: ${data.id}`, 20, 55);
    doc.text(`Date: ${new Date().toLocaleDateString('fr-FR')}`, 20, 62);
    doc.text(`Contact: ${data.user.email}`, 20, 69);
    
    // Titre principal
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text(data.title || 'Proposition de Partenariat EDUCAFRIC', 20, 85);
    
    // Contenu proposition
    doc.setFontSize(12);
    let yPosition = 105;
    
    const proposalContent = [
      'Cher partenaire,',
      '',
      'Nous vous proposons un partenariat stratégique avec EDUCAFRIC',
      'pour révolutionner l\'éducation en Afrique.',
      '',
      'Avantages du partenariat:',
      '• Accès au marché éducatif africain',
      '• Technologie éprouvée et adaptée',
      '• Support technique complet',
      '• Formation des équipes',
      '• Revenus partagés',
      '',
      'Nos références:',
      '• 156 écoles partenaires',
      '• 12,847 utilisateurs actifs',
      '• 87.5M CFA de revenus mensuels',
      '• 89.2% de taux de satisfaction',
      '',
      'Prochaines étapes:',
      '1. Présentation détaillée',
      '2. Négociation des termes',
      '3. Signature du contrat',
      '4. Déploiement pilote',
      '5. Expansion régionale'
    ];
    
    proposalContent.forEach(line => {
      if (yPosition > 260) {
        doc.addPage();
        yPosition = 30;
      }
      doc.text(line, 20, yPosition);
      yPosition += 8;
    });
    
    // Pied de page
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text('© 2025 EDUCAFRIC - Confidentiel', 20, 285);
      doc.text(`Page ${i}/${pageCount}`, 170, 285);
    }
    
    return Buffer.from(doc.output('arraybuffer'));
  }

  static async generateMultiRoleGuideDocument(data: DocumentData): Promise<Buffer> {
    const jsPDFModule = await import('jspdf');
    const jsPDF = jsPDFModule.default || jsPDFModule.jsPDF;
    const doc = new jsPDF();
    
    // Configuration
    doc.setFont('helvetica');
    
    // En-tête avec branding EDUCAFRIC
    doc.setFontSize(20);
    doc.setTextColor(0, 121, 242); // #0079F2
    doc.text('EDUCAFRIC', 20, 30);
    doc.setFontSize(14);
    doc.text('Système Multi-Rôle - Guide Commercial', 20, 40);
    
    // Ligne de séparation
    doc.setDrawColor(0, 121, 242);
    doc.setLineWidth(1);
    doc.line(20, 45, 190, 45);
    
    // Métadonnées document
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Document ID: ${data.id}`, 20, 55);
    doc.text(`Généré le: ${new Date().toLocaleDateString('fr-FR')}`, 20, 62);
    doc.text(`Généré par: ${data.user.email}`, 20, 69);
    doc.text(`Type: Guide Commercial Multi-Rôle`, 20, 76);
    
    // Titre principal
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text('Système Multi-Rôle EDUCAFRIC', 20, 90);
    doc.setFontSize(14);
    doc.text('Guide Commercial (Français / English)', 20, 100);
    
    // Section 1: Vue d'ensemble (Français)
    let yPosition = 120;
    doc.setFontSize(16);
    doc.setTextColor(0, 121, 242);
    doc.text('1. VUE D\'ENSEMBLE DU SYSTÈME', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const overviewContent = [
      'Le système multi-rôle EDUCAFRIC permet aux utilisateurs d\'avoir',
      'plusieurs rôles simultanément sur un seul compte, optimisant',
      'l\'expérience utilisateur et réduisant les coûts administratifs.',
      '',
      'Avantages clés:',
      '• Un seul compte pour plusieurs fonctions',
      '• Commutation instantanée entre les rôles',
      '• Isolation complète des données par rôle',
      '• Sécurité renforcée avec validation stricte',
      '• Réduction des coûts de gestion'
    ];
    
    overviewContent.forEach(line => {
      if (yPosition > 260) {
        doc.addPage();
        yPosition = 30;
      }
      doc.text(line, 25, yPosition);
      yPosition += 8;
    });
    
    // Section 2: Comment créer un rôle parent
    yPosition += 10;
    doc.setFontSize(16);
    doc.setTextColor(0, 121, 242);
    doc.text('2. CRÉATION D\'UN RÔLE PARENT', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const parentCreationSteps = [
      'Étapes pour ajouter un rôle parent à un compte commercial:',
      '',
      '1. Connectez-vous en tant que Commercial',
      '2. Accédez à "Gestion Multi-Rôle" dans le menu',
      '3. Cliquez sur "Ajouter un rôle Parent"',
      '4. Remplissez les informations de liaison:',
      '   - Numéro de téléphone de l\'enfant',
      '   - Nom complet de l\'enfant',
      '   - École de l\'enfant',
      '5. Validez la création du lien parent-enfant',
      '6. Le système crée automatiquement les permissions',
      '',
      'Sécurité:',
      '• Validation obligatoire de l\'école',
      '• Vérification du numéro de téléphone',
      '• Isolation totale des données commerciales'
    ];
    
    parentCreationSteps.forEach(line => {
      if (yPosition > 260) {
        doc.addPage();
        yPosition = 30;
      }
      doc.text(line, 25, yPosition);
      yPosition += 6;
    });
    
    // Nouvelle page pour la section anglaise
    doc.addPage();
    yPosition = 30;
    
    // Section English
    doc.setFontSize(16);
    doc.setTextColor(0, 121, 242);
    doc.text('3. MULTI-ROLE SYSTEM OVERVIEW (ENGLISH)', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const englishOverview = [
      'EDUCAFRIC\'s multi-role system allows users to have multiple',
      'roles simultaneously on a single account, optimizing user',
      'experience and reducing administrative costs.',
      '',
      'Key Benefits:',
      '• Single account for multiple functions',
      '• Instant role switching capability',
      '• Complete data isolation per role',
      '• Enhanced security with strict validation',
      '• Reduced management costs',
      '',
      'How to Add Parent Role to Commercial Account:',
      '',
      '1. Login as Commercial user',
      '2. Navigate to "Multi-Role Management"',
      '3. Click "Add Parent Role"',
      '4. Fill in linking information:',
      '   - Child\'s phone number',
      '   - Child\'s full name',
      '   - Child\'s school',
      '5. Validate parent-child connection',
      '6. System automatically creates permissions',
      '',
      'Security Features:',
      '• Mandatory school validation',
      '• Phone number verification',
      '• Complete commercial data isolation'
    ];
    
    englishOverview.forEach(line => {
      if (yPosition > 260) {
        doc.addPage();
        yPosition = 30;
      }
      doc.text(line, 25, yPosition);
      yPosition += 6;
    });
    
    // Section technique
    yPosition += 15;
    doc.setFontSize(16);
    doc.setTextColor(0, 121, 242);
    doc.text('4. SPÉCIFICATIONS TECHNIQUES', 20, yPosition);
    yPosition += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const technicalSpecs = [
      'Architecture du système:',
      '• Base de données: PostgreSQL avec isolation par rôle',
      '• Authentification: Session-based avec validation 2FA',
      '• Permissions: Matrix de contrôle d\'accès granulaire',
      '• APIs: RESTful avec validation de rôle par endpoint',
      '',
      'Limitations et contraintes:',
      '• Maximum 3 rôles par compte utilisateur',
      '• Validation obligatoire école-parent-enfant',
      '• Audit trail complet pour toutes les actions',
      '• Timeout de session: 24h pour sécurité',
      '',
      'Support technique:',
      '• Email: admin@educafric.com',
      '• Téléphone: +237 657 004 011',
      '• Documentation: /documents/systeme-multi-role'
    ];
    
    technicalSpecs.forEach(line => {
      if (yPosition > 260) {
        doc.addPage();
        yPosition = 30;
      }
      doc.text(line, 25, yPosition);
      yPosition += 8;
    });
    
    // Pied de page pour toutes les pages
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text('© 2025 EDUCAFRIC - Guide Commercial Multi-Rôle', 20, 285);
      doc.text(`Page ${i}/${pageCount}`, 170, 285);
    }
    
    return Buffer.from(doc.output('arraybuffer'));
  }
}