INSERT INTO classes (id, name, school_id, level) VALUES (15, 'Form 1A', 14, 'Terminale') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (16, 'Form 1B', 14, 'FIRST CIRCLE') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (17, 'Form 2', 14, 'FIRST CIRCLE') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (18, 'Form 3', 14, 'FIRST CIRCLE') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (19, 'Form 4', 14, 'FIRST CIRCLE') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (20, 'Form 5', 14, 'FIRST CIRCLE') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (21, 'Lower Sith', 14, 'SECOND CIRCLE') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (31, 'Lower Sixth A5', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (32, 'Lower Sixth Science S1', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (33, 'Lower Sixth Science S2', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (34, 'Lower Sixth Science S3', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (35, 'Lower Sixth Science S4', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (36, 'Lower Sixth Science S5', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (37, 'Upper Sixth A1', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (38, 'Upper Sixth A2', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (39, 'Upper Sixth A3', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (40, 'Upper Sixth A4', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (41, 'Upper Sixth A5', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (42, 'Upper Sixth Science S1', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (43, 'Upper Sixth Science S2', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (44, 'Upper Sixth Science S3', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (45, 'Upper Sixth Science S4', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (46, 'Upper Sixth Science S5', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (48, 'Form 2A', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (49, 'Form 2B', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (50, 'Form 3A', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (51, 'Form 3B', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (52, 'Form 4A', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (53, 'Form 4B', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (54, 'Form 5A', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (55, 'Form 5B', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (57, 'Form B1', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (58, 'Form A2', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (59, 'Form B2', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (60, 'Form A3', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (61, 'Form B3', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (62, 'Form A4', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (83, 'Form2B', 15, 'Sport') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (88, 'Lower Sixth A1', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (89, 'Lower Sixth A2', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (90, 'Lower Sixth A3', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (91, 'Lower Sixth A4', 10, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (92, 'Lower Sixth A1', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (93, 'Lower Sixth A2', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (94, 'Lower Sixth A3', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (95, 'Lower Sixth A4', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (96, 'Lower Sixth A5', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (97, 'Lower Sixth Science S1', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (98, 'Lower Sixth Science S2', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (99, 'Lower Sixth Science S3', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (100, 'Lower Sixth Science S4', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (101, 'Lower Sixth Science S5', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (102, 'Upper Sixth A1', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (103, 'Upper Sixth A2', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (104, 'Upper Sixth A3', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (105, 'Upper Sixth A4', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (106, 'Upper Sixth A5', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (107, 'Upper Sixth Science S1', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (108, 'Upper Sixth Science S2', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (109, 'Upper Sixth Science S3', 15, '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (112, 'Test 24', 15, 'Sport') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (113, 'Tle A4', 15, 'Français ') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (164, 'Tle', 15, 'Tle') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (165, 'Tle', 15, 'Tle') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (166, 'Tle', 15, 'Tle') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (167, 'Tle', 15, 'Tle') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (168, 'Tle', 15, 'Tle') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (169, 'Tle', 15, 'Tle') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (189, 'Classe BC', 15, 'Classe') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (190, 'Classe BC', 15, 'Classe') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (191, 'Classe BC', 15, 'Classe') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (192, 'Classe BC', 15, 'Classe') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (193, 'class BC', 15, 'class') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (194, 'class BC', 15, 'class') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (195, 'Classe 45', 15, 'Classe') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (199, 'Teste234', 15, 'Teste234') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (209, 'Techn', 16, 'Techn') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (210, 'Form 4A', 16, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (211, 'Form 5A', 16, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (212, 'Test Grade 1A', 15, 'Test') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (213, 'Form 1A', 16, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (214, 'Test class 12', 15, 'Test') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (215, 'Form 2A', 16, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (216, 'Form 1A', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (217, 'Form 1B', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (218, 'Form 1C', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (219, 'Form 1D', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (220, 'Form 1E', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (221, 'Form 1 Bilingual', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (222, 'Form 2A', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (223, 'Form 2B', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (224, 'Form 2C', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (225, 'Form 2D', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (226, 'Form 2E', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (228, 'Form 2 Bilingual', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (229, 'Form 3A', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (230, 'Form 3B', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (231, 'Form 3C', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (232, 'Form 3D', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (234, 'Form 3 Bilingual', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (235, 'Form 3E', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (236, 'Form 4A', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (237, 'Form 4B', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (238, 'Form 4C', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (239, 'Form 4D', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (240, 'Form 4 Bilingual', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (241, 'Form 5A', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (242, 'Form 5B', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (243, 'Form 5C', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (244, 'Form 5D', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (245, 'Form 5 Bilingual', 17, 'Form') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (246, 'Lower sixth A1', 17, 'Lower') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (247, 'Lower Sixth A2', 17, 'Lower') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (248, 'Lower Sixth A3', 17, 'Lower') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (249, 'Lower Sixth A4', 17, 'Lower') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (250, 'Lower sixth A5', 17, 'Lower') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (251, 'Lower sixth S1', 17, 'Lower') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (252, 'Lower Sixth S2', 17, 'Lower') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (253, 'Lower Sixth S3', 17, 'Lower') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (254, 'Lower Sixth S4', 17, 'Lower') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (255, 'Upper Sixth A1', 17, 'Upper') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (256, 'Upper Sixth A2', 17, 'Upper') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (257, 'Upper Sixth A3', 17, 'Upper') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (258, 'Upper Sixth A4', 17, 'Upper') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (259, 'Upper Sixth A5', 17, 'Upper') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (260, 'Upper Sixth S1', 17, 'Upper') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (261, 'Upper Sixth S2', 17, 'Upper') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (262, 'Upper Sixth S3', 17, 'Upper') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (263, 'Upper Sixth S4', 17, 'Upper') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
INSERT INTO classes (id, name, school_id, level) VALUES (264, 'Test Grade 9A', 15, 'Test') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, school_id = EXCLUDED.school_id, level = EXCLUDED.level;
